const ArcanumItemData = [
  { name: "...groth sprocket" },
  { name: "1800 coins (???)" },
  { name: "3600 gold" },
  { name: "Ancient Iron Drums" },
  { name: "Almstead's Axe" },
  { name: "Amulet - CHECK NAME" },
  { name: "Ancient Gun Chassis" },
  { name: "Arabalah's Sacred Artifact" },
  { name: "Baneful Gauntlets" },
  { name: "Basic Machined Plate" },
  { name: "Basic Platemail" },
  { name: "Bates Mausoleum Key" },
  { name: "Bessie Toone's Boot" },
  { name: "Boots of the Dark Toll" },
  { name: "Camera" },
  { name: "Cassie's Jewellery" },
  { name: "Chapeau of Magnetic Inversion" },
  { name: "Charmed Ring" },
  { name: "Charming Medallion" },
  { name: "Chest of Gold" },
  { name: "Crate of Ale" },
  { name: "Cynthia Boggs' Locket" },
  { name: "Derian Ka Sword" },
  { name: "Dragon Pool Key 2" },
  { name: "Dwarven Gauntlets" },
  { name: "Dynamite" },
  { name: "Elephant Gun" },
  { name: "Enchanted Looking Glass" },
  { name: "Envenomed Sword" },
  { name: "Fancy Ring" },
  { name: "Flawless Dwarven Rubies" },
  { name: "Funeral Stone" },
  { name: "Gem of Malachi Rench" },
  { name: "Gem of Water Purity" },
  { name: "Gift for Mrs. Regina Halster" },
  { name: "Gladys' Ring" },
  { name: "Golden Idol of Kree" },
  { name: "Great Ruby of K'alru" },
  { name: "Grunwalde's Poison" },
  { name: "Harrow" },
  { name: "Heavy Barbarian's Blade" },
  { name: "Helmet of Strength" },
  { name: "Heron Device" },
  { name: "Infernal Hammer" },
  { name: "Innkeeper's Key, Dernholm" },
  { name: "J.T. Morgan's Master Locksmith Tools" },
  { name: "Jewel Of Hebe" },
  { name: "Kerghan and Persephone" },
  { name: "Key for Stillwater Giant Case" },
  { name: "Key to Garret Almstead's Trunk" },
  { name: "Key to Lloyd Gurloes’ backroom" },
  { name: "Key to Ristezze’s Bedroom" },
  { name: "Key to the Back Room in 57 Mulligan Bone" },
  { name: "Key to the factory" },
  { name: "Key to the Gates of the Isle of Despair" },
  { name: "Key to the Shrouded Hills Bridge Gate" },
  { name: "Key to the Warehouse of the Small" },
  { name: "Key to Thorvald's Chest" },
  { name: "Key to Thorvald's House" },
  { name: "Lethe Wyvern Venom" },
  { name: "Levered Machine Gun" },
  { name: "Liam Cameron's Journal" },
  { name: "Looking Glass Rifle" },
  { name: "Lucky Medallion" },
  { name: "Lycanthrope Restorative" },
  { name: "Mace of the Damned" },
  { name: "Machined Gauntlets" },
  { name: "Machined Plate" },
  { name: "Madam Lil's Music Box" },
  { name: "Magick Shoppe Key. Tarant" },
  { name: "Magickal trap" },
  { name: "Magnus' Bracelet" },
  { name: "Mastery Medallion of Meta" },
  { name: "Mastery Medallion of Water" },
  { name: "Matchbook from Roseborough Inn" },
  { name: "Mechanical Dagger" },
  { name: "Medallion of Beauty" },
  { name: "Mithril Chainmail" },
  { name: "Mysterious Dwarven Gauntlets" },
  { name: "Mystic Traveler's Cloak", tier: "magick" },
  { name: "Napha Water" },
  { name: "Necklace of Queen K'na S'ea" },
  { name: "Negociator's Ring", tier: "magick" },
  { name: "Package for Jongle Dunne" },
  { name: "Plans For Schreck's Multi-barrel Pistol" },
  { name: "Post Bound For Tarant" },
  { name: "Potion Of Dark Power" },
  { name: "Power Axe" },
  { name: "Preston Radcliffe's Passport" },
  { name: "Purchase Order" },
  { name: "Random Arcane loot" },
  { name: "Ring of Concealment" },
  { name: "Ring of Silence" },
  { name: "Ring Of Virility" },
  { name: "Ristezze's File Cabinet Key" },
  { name: "Roseborough Inn Key" },
  { name: "Roseborough Inn Room Key" },
  { name: "Ryan Marshall's Police Record" },
  { name: "Shovel" },
  { name: "Shrouded Hills Bank Key" },
  { name: "Silver Boot Bucket" },
  { name: "Skull from the Tomb of Nasrudin" },
  { name: "Small Statuette" },
  { name: "Statue of the Goddess Geshtianna" },
  { name: "Stillwater Giant Pelt" },
  { name: "Stringy Pete's Treasure" },
  { name: "Tempered Shield" },
  { name: "The Skulls of the Ren'ar Siamese Twins" },
  { name: "Trevor Lynwood's Camera" },
  { name: "Unidentified Boots" },
  { name: "Unidentified ring" },
  { name: "Unidentified Staff" },
  { name: "Vernon's key" },
  { name: "Wheel Clan Spectacles" },
  { name: "White scarf" },
  { name: "Will-O-The-Wisp Essence" },

  // MAGICK
  { name: "Amulet of N’Tala", tier: "magick" },
  { name: "Arcane Axe", tier: "magick" },
  { name: "Arcane Bow", tier: "magick" },
  { name: "Arcane Gauntlets", tier: "magick" },
  { name: "Arcane Ring", tier: "magick" },
  { name: "Arcane Robes", tier: "magick" },
  { name: "Arcane Staff", tier: "magick" },
  { name: "Arcane Sword", tier: "magick" },
  { name: "Ashen Robes", tier: "magick" },
  { name: "Blessed Bow", tier: "magick" },
  { name: "Dagger of Speed", tier: "magick" },
  { name: "Divining Staff", tier: "magick" },
  { name: "Ellumyn's Bow", tier: "magick" },
  { name: "Elven Hunter Bow", tier: "magick"  },
  { name: "Enchanted Gown", tier: "magick" },
  { name: "Mage’s Dagger", tier: "magick" },
  { name: "Mage's Staff", tier: "magick" },
  { name: "Magick Bow", tier: "magick" },
  { name: "Magick Necklace", tier: "magick" },
  { name: "Magick Ring", tier: "magick" },
  { name: "Magick Robes", tier: "magick" },
  { name: "Ring of Poison Resistance", tier: "magick" },
  { name: "Ring of Protection", tier: "magick" },
  { name: "Robe of Fire Protection", tier: "magick" },
  { name: "Screaming Scimtar", tier: "magick" },
  { name: "Screaming Shield", tier: "magick" },
  { name: "Shaman's Staff", tier: "magick" },
  { name: "Shocking Dagger", tier: "magick" },
  { name: "Staff of Healing", tier: "magick" },
  { name: "Stillwater Blade", tier: "magick" },
  { name: "Sword of Baltar", tier: "magick" },
  { name: "Witch's Dagger", tier: "magick" },

  // MAGICK - SCROLL
  { name: "Scroll of Bonds of Magic", tier: "magick" },
  { name: "Scroll of Call Air Elemental", tier: "magick" },
  { name: "Scroll of Call Earth Elemental", tier: "magick" },
  { name: "Scroll of Call Water Elemental", tier: "magick" },
  { name: "Scroll of Disarm", tier: "magick" },
  { name: "Scroll of Disperse Magick", tier: "magick" },
  { name: "Scroll of Flesh to Stone", tier: "magick" },
  { name: "Scroll of Major Healing", tier: "magick" },
  { name: "Scroll of Polymorph", tier: "magick" },
  { name: "Scroll of Sense Invisible/Traps", tier: "magick" },
  { name: "Scroll of Squall of Ice", tier: "magick" },
  { name: "Scroll of Summon Undead", tier: "magick" },
  { name: "Scroll of Teleportation", tier: "magick" },

  // HEXED
  { name: "Blade of Vicious Haste", tier: "hexed" },
  { name: "Consuming Plate Mail", tier: "hexed" },
  { name: "Helmet of Yzar's Cost", tier: "hexed" },
  { name: "Hero's Weakness Barbarian Armor", tier: "hexed" },
  { name: "Hexed Dagger", tier: "hexed" },
  { name: "Hexed Leather Armour", tier: "hexed" },
  { name: "Serpentine Necklace", tier: "hexed" },
  { name: "Shadow Hand Dagger", tier: "hexed" },

  // NOTES & BOOKS
  { name: "BOOK The Curse of T'sen-Ang" },
  { name: "Creature Compendium by Sir Maxwell III" },
  { name: "Joachim’s Note to Virgil", image: "Textures/Notes/1080 - Joachim's Note to Virgil.png" },
  { name: "Journal of Gilbert Bates" },
  { name: "Horror Among the Dark Elves" },
  { name: "Map of Tarantian Sewers" },
  { name: "Map: The Place of Lost Voices" },
  { name: "Note (Safe Combination)", image: "Textures/Notes/1040 - Safe Combination.png" },
  { name: "Note discrepensy archaeon" },
  { name: "Note from M'in Gorad" },
  { name: "Note to M'in Gorad from K'an Hua", image: "Textures/Notes/1030 - Note to M'in Gorad from K'an Hua.png" },
  { name: "Note: The IFS Zephyr has crashed", image: "Textures/Notes/1150 - William Radcliffe.png" },
  { name: "Prowling Master Note 3", image: "Textures/Notes/1120 - Prowling Master 3.png" },
  { name: "Ristezze's Map" },
  { name: "Roan's Almanac of All Things Dwarven" },
  { name: "Telegram" },
  { name: "The Hand" },
  { name: "Thorvald's Journal" },
  { name: "Tannon Wroughtbringer's Journal" },
  { name: "Tyron's Note", image: "Textures/Notes/1190 - Tyron's Note.png" },
  { name: "Wilhemina's Note to Jared", image: "Textures/Notes/1160 - Wilhemina's note to Jared.png" },

  // SCHEMATICS
  { name: "Schematics: Automaton" },
  { name: "Schematics: Wheel Clan Spectacles" },
];
