const ArcanumItemData = [

  // ARMOR
  { name: "Arcane Chainmail", itemimg: "arcanechainmail.gif" },
  { name: "Arcane Leather Armour", itemimg: "arcaneleatherarmour.gif" },
  { name: "Basic Machined Plate", itemimg: "basicmachinedplate.gif" },
  { name: "Basic Platemail", itemimg: "basicplatemail.gif" },
  { name: "Bronzed Plate", itemimg: "BronzedPlate.png" },
  { name: "Caladon Elite Guard Chainmail", itemimg: "caladoneliteguardchainmail.gif" },
  { name: "Chainmail", itemimg: "chainmail.gif" },
  { name: "Charmed Platemail", itemimg: "charmedplatemail.gif" },
  { name: "Consuming Plate Mail", tier: "hexed", itemimg: "BronzedPlate.png" },
  { name: "Creep Armour", itemimg: "creeparmour.gif" },
  { name: "Diseased Leather Armour", itemimg: "leatherarmour.gif" },
  { name: "Dragon Skin Leather", itemimg: "dragonskinleather.gif" },
  { name: "Dread Armour", itemimg: "dreadarmour.gif" },
  { name: "Dwarven Chainmail", itemimg: "dwarvenchainmail.gif" },
  { name: "Dwarven Platemail", itemimg: "dwarvenplatemail.gif" },
  { name: "Elite Plate", itemimg: "eliteplate.gif" },
  { name: "Elven Chainmail", itemimg: "elvenchainmail.gif" },
  { name: "Feather-Weight Chain", itemimg: "featherweightchain.gif" },
  { name: "Gnomish Chainmail", itemimg: "gnomishchainmail.gif" },
  { name: "Large Leather Armour", itemimg: "largeleatherarmour.gif" },
  { name: "Large Mystic Leather Armour", itemimg: "largemysticleatherarmour.gif" },
  { name: "Large Studded Armour", itemimg: "largestuddedarmour.gif" },
  { name: "Leather Armour", itemimg: "leatherarmour.gif" },
  { name: "Magick Leather Armour", itemimg: "magickleatherarmour.gif" },
  { name: "Minute Platemail of Regeneration", itemimg: "minuteplatemailofregeneration.gif" },
  { name: "Mithril Chainmail", itemimg: "mithrilchainmail.gif" },
  { name: "Mystic Chainmail", itemimg: "mysticchainmail.gif" },
  { name: "Mystic Platemail", itemimg: "mysticplatemail.gif" },
  { name: "Oiled Chainmail", itemimg: "oiledchainmail.gif" },
  { name: "Oiled Thives Leather", itemimg: "oiledthievesleather.gif" },
  { name: "Small Arcane Leather Armour", itemimg: "smallarcaneleatherarmour.gif" },
  { name: "Small Basic Platemail", itemimg: "smallbasicplatemail.gif" },
  { name: "Small Chainmail", itemimg: "smallchainmail.gif" },
  { name: "Small Charmed Platemail", itemimg: "smallcharmedplatemail.gif" },
  { name: "Small Leather Armour", itemimg: "smallleatherarmour.gif" },
  { name: "Small Machined Platemail", itemimg: "smallmachinedplatemail.gif" },
  { name: "Small Magick Leather Armour", itemimg: "smallmagickleatherarmour.gif" },
  { name: "Small Magick Platemail", itemimg: "smallmagicplatemail.gif" },
  { name: "Small Mithril Chainmail", itemimg: "smallmithrilchainmail.gif" },
  { name: "Small Mystic Chainmail", itemimg: "smallmysticchainmail.gif" },
  { name: "Small Mystic Leather Armour", itemimg: "smallmysticleatherarmour.gif" },
  { name: "Small Mystic Platemail", itemimg: "smallmysticplatemail.gif" },
  { name: "Small Oiled Chainmail", itemimg: "smalloiledchainmail.gif" },
  { name: "Small Studded Leather", itemimg: "smallstuddedleather.gif" },
  { name: "Studded Leather", itemimg: "studdedleather.gif" },

  // CLOTHES
  { name: "Arcane Robes", itemimg: "arcanerobes.gif" },
  { name: "Charmed Small Robes", itemimg: "charmedsmallrobes.gif" },
  { name: "Enchanted Gown", itemimg: "sundaysbestdress.gif" },
  { name: "Heavy Rags", itemimg: "heavyrags.gif" },
  { name: "Heavy Wool Clothes", itemimg: "heavywoolclothes.gif" },
  { name: "Jacket", itemimg: "jacket.gif" },
  { name: "Large Manservant's Uniform", itemimg: "largemanservantsuniform.gif" },
  { name: "Large Nice Suit", itemimg: "largenicesuit.gif" },
  { name: "Large Venom-Shielded Garment", itemimg: "largevenomshieldedgarment.gif" },
  { name: "Magick Robes", itemimg: "magickrobes.gif" },
  { name: "Mystic Traveller's Cloak", itemimg: "mystictravellerscloak.gif" },
  { name: "Nice Suit", itemimg: "nicesuit.gif" },
  { name: "Plain Dress", itemimg: "plaindress.gif" },
  { name: "Priest Robes", itemimg: "priestrobes.gif" },
  { name: "Robes", itemimg: "robes.gif" },
  { name: "Rustic Dress", itemimg: "rusticdress.gif" },
  { name: "Rustic Finery", itemimg: "rusticfinery.gif" },
  { name: "Servant's Clothes", itemimg: "servantsclothes.gif" },
  { name: "Servant's Dress", itemimg: "servantsdress.gif" },
  { name: "Shadowing Robes", itemimg: "shadowingrobes.gif" },
  { name: "Silent Robes", itemimg: "magickrobes.gif" },
  { name: "Small Arcane Traveller's Cloak", itemimg: "smallarcanetravellerscloak.gif" },
  { name: "Small Charmed Robes", itemimg: "smallcharmedrobes.gif" },
  { name: "Small Heavy Wool Clothes", itemimg: "smallheavywoolclothes.gif" },
  { name: "Small Magick Robes", itemimg: "smallmagickrobes.gif" },
  { name: "Small Manservant's Clothes", itemimg: "smallmanservantsclothes.gif" },
  { name: "Small Nice Suit", itemimg: "smallnicesuit.gif" },
  { name: "Small Priest Robes", itemimg: "smallmagickrobes.gif" },
  { name: "Small Robe of the Chameleon", itemimg: "smallrobeofthechameleon.gif" },
  { name: "Small Robes", itemimg: "smallrobes.gif" },
  { name: "Small Smoking Jacket", itemimg: "smallsmokingjacket.gif" },
  { name: "Small Suede Jacket", itemimg: "smallsuedejacket.gif" },
  { name: "Small Wool Jacket", itemimg: "smallwooljacket.png" },
  { name: "Smoking Jacket", itemimg: "smokingjacket.gif" },
  { name: "Suade Jacket", itemimg: "suadejacket.gif" },
  { name: "Suit of Resistance", itemimg: "nicesuit.gif" },
  { name: "''Sunday's Best'' Dress", itemimg: "sundaysbestdress.gif" },
  { name: "Venomous Robes", itemimg: "venomousrobes.gif" },
  { name: "Venom-Shielded Garment", itemimg: "venomshieldedgarment.gif" },
  { name: "Wool Jacket", itemimg: "wooljacket.gif" },

  // HELMETS
  { name: "Chapeau of Magnetic Inversion", itemimg: "chapeauofmagneticinversion.gif" },
  { name: "Dark Helm", itemimg: "darkhelm.gif" },
  { name: "Eye Gear", itemimg: "eyegear.gif" },
  { name: "Eye Glasses", itemimg: "eyeglasses.gif" },
  { name: "Fine Helmet", itemimg: "finehelmet.gif" },
  { name: "Geleam's Helm", itemimg: "geleamshelm.gif" },
  { name: "Goggled Helmet", itemimg: "goggledhelmet.gif" },
  { name: "Great Helm", itemimg: "greathelm.gif" },
  { name: "Helmet", itemimg: "helmet.gif" },
  { name: "Helmet of Strength", itemimg: "helmet.gif" }, // Not magick
  { name: "Helmet of Vision", itemimg: "helmetofvision.gif" },
  { name: "Helm of Light", itemimg: "helmoflight.gif" },
  { name: "Miner's Helmet", itemimg: "minershelmet.gif" },
  { name: "Nature's Wrath Helm", itemimg: "natureswrathhelm.gif" },
  { name: "Pig Face Basset", itemimg: "pigfacebasset.gif" },
  { name: "Top Hat", itemimg: "tophat.gif" },

  // BOOTS
  { name: "Boots", itemimg: "boots.gif" },
  { name: "Boots of the Dark Toll", itemimg: "bootsofthedarktoll.gif" },
  { name: "Elven Boots", itemimg: "elvenboots.gif" },
  { name: "Enchanted War Boots", itemimg: "enchantedwarboots.gif" },
  { name: "Fine Stout Boots", itemimg: "finestoutboots.gif" },
  { name: "Ladies Fancy Boots", itemimg: "ladiesfancyboots.gif" },
  { name: "Metal Boots", itemimg: "metalboots.gif" },
  { name: "Shoes", itemimg: "shoes.gif" },
  { name: "Worn Boots", itemimg: "wornboots.gif" },
  { name: "Worn Ladies Boots", itemimg: "wornladiesboots.gif" },
  { name: "Worn Shoes", itemimg: "wornshoes.gif" },

  // GLOVES
  { name: "Arcane Gauntlets", itemimg: "arcanegauntlets.gif" },
  { name: "Baneful Gauntlets", itemimg: "gauntlets.gif" },
  { name: "Chain Gloves", itemimg: "chaingloves.gif" },
  { name: "Charmed Gauntlets", itemimg: "charmedgauntlets.gif" },
  { name: "Dwarven Gauntlets", itemimg: "dwarvengauntlets.gif" },
  { name: "Gauntlets", itemimg: "gauntlets.gif" },
  { name: "Gloves of Dexterity", itemimg: "glovesofdexterity.gif" },
  { name: "Leather Gloves", itemimg: "leathergloves.gif" },
  { name: "Light-Fingered Gauntlets", itemimg: "lightfingeredgauntlets.gif" },
  { name: "Machined Gauntlets", itemimg: "machinedgauntlets.gif" },
  { name: "Vendigrothian Padded Leather Gloves", itemimg: "vendigrothianpaddedleathergloves.gif" },
  { name: "Vendigrothian War Gauntlets", itemimg: "vendigrothianwargauntlets.gif" },
  { name: "War Gauntlets", itemimg: "wargauntlets.gif" },
  { name: "Mysterious Dwarven Gauntlets" }, // TO ADD

  // SHIELDS
  { name: "Arcane Shield", itemimg: "arcaneshield.gif" },
  { name: "Battered Wooden Shield", itemimg: "batteredwoodenshield.gif" },
  { name: "Chill Shield", itemimg: "qualityironshield.gif" },
  { name: "Dented Iron Shield", itemimg: "dentedironshield.gif" },
  { name: "Flow Disruptor Shield", itemimg: "flowdisruptorshield.gif" },
  { name: "Kite Shield", itemimg: "kiteshield.gif" },
  { name: "Screaming Shield", itemimg: "qualityironshield.gif" },
  { name: "Quality Iron Shield", itemimg: "qualityironshield.gif" },
  { name: "Shadow Shield", itemimg: "shadowshield.gif" },
  { name: "Shield of Force", itemimg: "shieldofforce.gif" },
  { name: "Tempered Shield", itemimg: "qualityironshield.gif" }, // Not magick
  { name: "Wooden Shield", itemimg: "woodenshield.gif" },

  // RING
  { name: "Ring of Concealment" }, // Not magick
  { name: "Ring of Silence" }, // Mrs Morgan ring - magick
  { name: "Negociator's Ring", tier: "magick" },
  { name: "Ring of Poison Resistance", tier: "magick", itemimg: "FatedRing.png" },
  { name: "Ring of Protection", tier: "magick", itemimg: "RingofProtection.png" },

  // NECKLACE

  // AXES
  { name: "Almstead's Axe", itemimg: "qualityaxe.gif" },
  { name: "Arcane Axe", itemimg: "ArcaneAxe.png"},
  { name: "Axe", itemimg: "axe.gif" },
  { name: "Axe of Dark Lightning", itemimg: "axeofdarklightning.gif" },
  { name: "Axe of Lost Time", itemimg: "axeoflosttime.gif" },
  { name: "Axe of Strength", itemimg: "axeofstrength.gif" },
  { name: "Charged Axe", itemimg: "chargedaxe.gif" },
  { name: "Charmed Axe", itemimg: "charmedaxe.gif" },
  { name: "Envenomed Axe", itemimg: "" },
  { name: "Feather-Weight Axe", itemimg: "featherweightaxe.gif" },
  { name: "Mystic Axe", itemimg: "mysticaxe.gif" },
  { name: "Power Axe", itemimg: "poweraxe.gif" },
  { name: "Pyrotechnic Axe", itemimg: "pyrotechnicaxe.gif" },
  { name: "Quality Axe", itemimg: "qualityaxe.gif" },

  // FIREARMS
  { name: "Bronwyck's Gun", itemimg: "bronwycksgun.gif" },
  { name: "Clarington Rifle", itemimg: "claringtonrifle.gif" },
  { name: "Droch's Warbringer", itemimg: "drochswarbringer.gif" },
  { name: "Fancy Pistol", itemimg: "fancypistol.gif" },
  { name: "Fine Revolver", itemimg: "finerevolver.gif" },
  { name: "Flintlock Pistol", itemimg: "flintlockpistol.gif" },
  { name: "Hand Cannon", itemimg: "handcannon.gif" },
  { name: "Hand Crafted Flinklock", itemimg: "handcraftedflintlock.gif" },
  { name: "Hunting Rifle", itemimg: "huntingrifle.gif" },
  { name: "Large Bore Vendigrothian Rifle", itemimg: "largeborevendigrothianrifle.gif" },
  { name: "Long Range Rifle", itemimg: "rifle.gif" },
  { name: "Looking Glass Rifle", itemimg: "lookingglassrifle.gif" },
  { name: "Marksman Rifle", itemimg: "marksmanrifle.gif" },
  { name: "Old Flintlock Pistol", itemimg: "oldflintlockpistol.gif" },
  { name: "Old Revolver", itemimg: "oldrevolver.gif" },
  { name: "Repeater Rifle", itemimg: "repeaterrifle.gif" },
  { name: "Revolver", itemimg: "revolver.gif" },
  { name: "Rifle", itemimg: "rifle.gif" },
  { name: "Rusted Rifle", itemimg: "rustedrifle.gif" },
  { name: "Sharp Shooter's Pistol", itemimg: "finerevolver.gif" },
  { name: "Shotgun", itemimg: "shotgun.gif" },

  // MACES
  { name: "Charmed Mace", itemimg: "charmedmace.gif" },
  { name: "Mace", itemimg: "mace.gif" },
  { name: "Mace of the Damned", itemimg: "maceofthedamned.gif" },
  { name: "Magick Mace", itemimg: "magickmace.gif" },
  { name: "Quality Mace", itemimg: "qualitymace.gif" },
  { name: "Rusty Mace", itemimg: "rustymace.gif" },

  // STAFF
  { name: "Charmed Staff", itemimg: "charmedstaff.gif" },
  { name: "Diving Staff", itemimg: "staff.gif" },
  { name: "Mage's Staff", itemimg: "staff.gif" },
  { name: "Magick Staff", itemimg: "magickstaff.gif" },
  { name: "Quality Staff", itemimg: "qualitystaff.gif" },
  { name: "Righteous Staff", itemimg: "staff.gif" },
  { name: "Shaman's Staff", itemimg: "shamansstaff.gif" },
  { name: "Staff", itemimg: "staff.gif" },
  { name: "Staff of Healing", itemimg: "staff.gif" },
  { name: "Staff of Hypocrisy", itemimg: "staffofhypocrisy.gif" },
  { name: "Staff of Xoranth", itemimg: "staff.gif" },

  // DAGGERS
  { name: "Bone Dagger", itemimg: "bonedagger.gif" },
  { name: "Dagger", itemimg: "dagger.gif" },
  { name: "Dagger of Pain", itemimg: "dagger.gif" },
  { name: "Dagger of Speed", itemimg: "daggerofspeed.gif" },
  { name: "Dread Dagger", itemimg: "dagger.gif" },
  { name: "Finely Crafted Dagger", itemimg: "finelycrafteddagger.gif" },
  { name: "Finely Honed Dagger", itemimg: "dagger.gif" },
  { name: "Fine Steel Dagger", itemimg: "finesteeldagger.gif" },
  { name: "Fool's Dagger", itemimg: "daggerofspeed.gif" },
  { name: "Hexed Dagger", itemimg: "hexeddagger.gif" },
  { name: "Life Stealer Dagger", itemimg: "dagger.gif" },
  { name: "Mage's Dagger", itemimg: "magesdagger.gif" },
  { name: "Mechanical Dagger", itemimg: "mechanicaldagger.gif" },
  { name: "Rusty Dagger", itemimg: "rustydagger.gif" },
  { name: "Shadow Hand Dagger", itemimg: "shadowhanddagger.gif" },
  { name: "Shocking Dagger", itemimg: "dagger.gif" },
  { name: "Witch's Dagger", itemimg: "dagger.gif" },

  // HAMMERS
  { name: "Crushing Hammer", itemimg: "crushinghammer.gif" },
  { name: "Dwarven Hammer", itemimg: "qualityhammer.gif" },
  { name: "Hammer", itemimg: "hammer.gif" },
  { name: "Inferno Hammer", itemimg: "infernohammer.gif" },
  { name: "Lloyd's Hammer", itemimg: "qualityhammer.gif" },
  { name: "Machined Hammer", itemimg: "machinedhammer.gif" },
  { name: "Malloy's Peacemaker", itemimg: "qualityhammer.gif" },
  { name: "Quality Hammer", itemimg: "qualityhammer.gif" },
  { name: "Rusty Hammer", itemimg: "rustyhammer.gif" },

  // RANGED
  { name: "Bladed Boomerang", itemimg: "bladedboomerang.gif" },
  { name: "Blessed Bow", itemimg: "bow.gif" },
  { name: "Boomerang", itemimg: "boomerang.gif" },
  { name: "Bow", itemimg: "bow.gif" },
  { name: "Bow of Damage", itemimg: "bow.gif" },
  { name: "Bow of Terror", itemimg: "bowofterror.gif" },
  { name: "Bow of the Chill Reaper", itemimg: "bowofthechillreaper.gif" },
  { name: "Chakram", itemimg: "chakram.gif" },
  { name: "Charmed Bow", itemimg: "charmedbow.gif" },
  { name: "Compound Bow", itemimg: "compoundbow.gif" },
  { name: "Ellumyn's Bow", itemimg: "elvenhuntersbow.gif" },
  { name: "Elven Hunter's Bow", itemimg: "elvenhuntersbow.gif" },
  { name: "Fleet Boomerang", itemimg: "bladedboomerang.gif" },
  { name: "Hurtful Long Bow", itemimg: "hurtfullongbow.gif" },
  { name: "Long Bow", itemimg: "longbow.gif" },
  { name: "Magick Bow", itemimg: "magickbow.gif" },
  { name: "Serrated Chakram", itemimg: "serratedchakram.gif" },
  { name: "Short Bow", itemimg: "shortbow.gif" },
  { name: "Throwing Dagger", itemimg: "throwingdagger.gif" },

  // SWORDS
  { name: "Arcane Great Sword", itemimg: "arcanegreatsword.gif" },
  { name: "Arcane Sword", tier: "magick", itemimg: "bladeofunholyfire.gif" },
  { name: "Balanced Sword", itemimg: "balancedsword.gif" },
  { name: "Barbarian's Heavy Blade", itemimg: "barbariansheavyblade.gif" },
  { name: "Black Stone Blade", itemimg: "sword.gif" },
  { name: "Blade of Malevolent Storm", itemimg: "broadsword.gif" },
  { name: "Blade of Unholy Fire", itemimg: "bladeofunholyfire.gif" },
  { name: "Broadsword", itemimg: "broadsword.gif" },
  { name: "Caladon Elite Sword", itemimg: "caladonelitesword.gif" },
  { name: "Charmed Great Sword", itemimg: "charmedgreatsword.gif" },
  { name: "Charmed Sword", itemimg: "charmedsword.gif" },
  { name: "Claymore", itemimg: "claymore.gif" },
  { name: "Enchanted Sword", itemimg: "enchantedsword.gif" },
  { name: "Envenomed Sword", itemimg: "envenomedsword.gif" },
  { name: "Falchion", itemimg: "falchion.gif" },
  { name: "Filament Sword", itemimg: "filamentsword.gif" },
  { name: "Flamberge", itemimg: "flamberge.gif" },
  { name: "Katana", itemimg: "katana.gif" },
  { name: "Kite Sword", itemimg: "kitesword.gif" },
  { name: "Kryggird's Falchion", itemimg: "kryggirdsfalchion.gif" },
  { name: "Lingering Sword", itemimg: "caladonelitesword.gif" },
  { name: "Mystic Great Sword", itemimg: "mysticgreatsword.gif" },
  { name: "Mystic Sword", itemimg: "mysticsword.gif" },
  { name: "Quality Broadsword", itemimg: "qualitybroadsword.gif" },
  { name: "Quality Sword", itemimg: "qualitysword.gif" },
  { name: "Rapier", itemimg: "rapier.gif" },
  { name: "Rusty Sword", itemimg: "rustysword.gif" },
  { name: "Scimitar", itemimg: "scimitar.gif" },
  { name: "Screaming Scimitar", itemimg: "scimitar.gif" },
  { name: "Short Sword", itemimg: "shortsword.gif" },
  { name: "Stillwater Blade", itemimg: "stillwaterblade.gif" },
  { name: "Sword", itemimg: "sword.gif" },
  { name: "Sword of Air", itemimg: "swordofair.gif" },
  { name: "Sword of Baltar", itemimg: "qualitybroadsword.gif" },
  { name: "Sword of Defense", itemimg: "swordofdefense.gif" },
  { name: "Sword of Sickness", itemimg: "swordofsickness.gif" },
  { name: "Tempered Sword", itemimg: "sword.gif" },
  { name: "The Bangellian Scourge", tier: "hexed", itemimg: "BangellianScourge.png" },
  { name: "Torian Kel's Ancestral Sword", itemimg: "toriankelsancestralsword.gif" },

  // CHEMICALS
  { name: "Anaesthisizer", itemimg: "" },
  { name: "Animal Scent", itemimg: "" },
  { name: "Brewer's Yeast", itemimg: "brewersyeast.gif" },
  { name: "Charges", itemimg: "" },
  { name: "Corrosive Acid", itemimg: "corrosiveacid.gif" },
  { name: "Dragon's Cologne", itemimg: "dragonscologne.gif" },
  { name: "Electrolyte Solution", itemimg: "electrolytesolution.gif" },
  { name: "Fortifier", itemimg: "" },
  { name: "Hallucinite", itemimg: "" },
  { name: "Mental Inhibitor", itemimg: "" },
  { name: "Monroe's Cleaner", itemimg: "monroescleaner.gif" },
  { name: "Morning Star Perfume", itemimg: "morningstarperfume.gif" },
  { name: "Mushrooms", itemimg: "mushrooms.gif" },
  { name: "Necromizer", itemimg: "" },
  { name: "Paralyzer", itemimg: "" },
  { name: "Pete's Carbolic Acid", itemimg: "petescarbolicacid.gif" },
  { name: "Potion of Paralysis", itemimg: "" },
  { name: "Stong Poison", itemimg: "strongpoison.gif" },
  { name: "Sulphur Pills", itemimg: "sulphurpills.gif" },
  { name: "Varham's Aqua Vitae", itemimg: "varhamsaquavitae.gif" },

  // HERBS
  { name: "Accelerate Healing", itemimg: "acceleratehealing.gif" },
  { name: "Big Chief Snake Oil", itemimg: "bigchiefsnakeoil.gif" },
  { name: "Coca Leaves", itemimg: "cocaleaves.gif" },
  { name: "Cure All", itemimg: "cureall.gif" },
  { name: "Cure Poison", itemimg: "curepoison.gif" },
  { name: "Fatigue Limiter", itemimg: "fatiguelimiter.gif" },
  { name: "Fatigue Restorer", itemimg: "fatiguerestorer.gif" },
  { name: "Ginka Root", itemimg: "ginkaroot.gif" },
  { name: "Healing Salve", itemimg: "healingsalve.gif" },
  { name: "Invigorator", itemimg: "invigorator.gif" },
  { name: "Kadura Stem", itemimg: "kadurastem.gif" },
  { name: "Miracle Cure", itemimg: "" },
  { name: "Poppy Flowers", itemimg: "poppyflowers.gif" },
  { name: "Reanimator", itemimg: "reanimator.gif" },
  { name: "Restore Life", itemimg: "restorelife.gif" },
  { name: "Tobacco Leaves", itemimg: "tobaccoleaves.gif" },
  { name: "Venom", itemimg: "venom.gif" },
  { name: "Witchbane", itemimg: "witchbane.gif" },
  { name: "Wonder Drug", itemimg: "wonderdrug.gif" },

  // MISCELLANEOUS
  { name: "Compass", itemimg: "compass.gif" },
  { name: "Engine Muffler", itemimg: "enginemuffler.gif" },
  { name: "Key Ring", itemimg: "keyring.gif" },
  { name: "Lantern", itemimg: "lantern.gif" },
  { name: "Large Pipe", itemimg: "largepipe.gif" },
  { name: "Leather Straps", itemimg: "leatherstraps.gif" },
  { name: "Liquid Soap", itemimg: "liquidsoap.gif" },
  { name: "Looking Glass", itemimg: "lookingglass.gif" },
  { name: "Metal Can", itemimg: "metalcan.gif" },
  { name: "Oak Axe Handle", itemimg: "oakaxehandle.gif" },
  { name: "Pocket Watch", itemimg: "pocketwatch.gif" },
  { name: "Rag", itemimg: "rag.gif" },
  { name: "Ruby Gem", itemimg: "Gem_Ruby.png" },
  { name: "Shovel", itemimg: "shovel.gif" },
  { name: "Small Metal Tube", itemimg: "smallmetaltube.gif" },

  // QUEST
  { name: "Amulet of N'Tala", itemimg: "amuletofntala.gif", tier: "magick" },
  { name: "Arbalah's Sacred Artifact", itemimg: "arbalahssacredartifact.gif" },
  { name: "Bessie Toone's Boot", itemimg: "bessietoonesboot.gif" },
  { name: "Blade of Xerxes", itemimg: "dagger01.png" },
  { name: "Camera", itemimg: "camera.gif" },
  { name: "Case of Ale", itemimg: "caseofale.gif" },
  { name: "Case of Whiskey", itemimg: "" },
  { name: "Chest of Gold", itemimg: "chestofgold.gif" },
  { name: "Crystal Ball", itemimg: "crystalball.gif" },
  { name: "Empty Vial", itemimg: "emptyvial.gif" },
  { name: "Eyes of Sir Garrick Stout", itemimg: "eyesofsirgarrickstout.gif" },
  { name: "Deed to the Bessie Toone Mine", itemimg: "minedeed.gif" },
  { name: "Gem of Malachi Rench", itemimg: "gemofmalachirench.gif" },
  { name: "Gift for Mrs. Regina Halster", itemimg: "giftformrsreginahalster.gif" },
  { name: "Gladys' Ring", itemimg: "gladysring.gif" },
  { name: "Golden Idol of Kree", itemimg: "goldenidolofkree.gif" },
  { name: "J.T. Morgan's Master Locksmith Tools", itemimg: "jtmorgansmasterlocksmithtools.gif" },
  { name: "Kerghan and Persephone", itemimg: "kerghanandpersephone.gif" },
  { name: "Magical Trap", itemimg: "magicaltrap.gif" },
  { name: "Norian's Potato Moonshine", itemimg: "norianspotatomoonshine.gif" },
  { name: "Old Sprocket", itemimg: "oldsprocket.gif" },
  { name: "Package for Jongle Dunne", itemimg: "packageforjongledunne.gif" },
  { name: "Potion to Heal the Blind", itemimg: "potiontohealtheblind.gif" },
  { name: "Skulls of the Ren'ar Siamese Twins", itemimg: "skullsoftherenarsiamesetwins.gif" },
  { name: "Statue of the Goddess Geshitianna", itemimg: "statueofthegoddessgeshitianna.gif" },
  { name: "Stillwater Giant Pelt", itemimg: "stillwatergiantpelt.gif" },
  { name: "Stillwater Trap", itemimg: "stillwatertrap.gif" },
  { name: "Toy Train", itemimg: "toytrain.gif" },
  { name: "Trevor Lynwood's Camera", itemimg: "trevorlynwoodscamera.gif" },
  { name: "T'sen Ang: Horror Among the Dark Elves", itemimg: "thehand.gif" },
  { name: "Vendigroth Device", itemimg: "vendigrothdevice.gif" },
  { name: "Vial of Dragon's Blood", itemimg: "vialofdragonsblood.gif" },
  { name: "Volar's Wisp Essence", itemimg: "volarswispessence.gif" },
  { name: "Wheel Clan Spectacles", itemimg: "wheelclanspectacles.gif" },

  // FOOD
  { name: "Absinthe", itemimg: "absinthe.gif" },
  { name: "Bread", itemimg: "bread.gif" },
  { name: "CK Sugar", itemimg: "cksugar.gif" },
  { name: "Dwarven Snuff", itemimg: "dwarvensnuff.gif" },
  { name: "Earl Grey Tea", itemimg: "earlgreytea.gif" },
  { name: "Elven Spring Water", itemimg: "elvenspringwater.gif" },
  { name: "Sweet Cakes", itemimg: "sweetcakes.gif" },
  { name: "Water", itemimg: "water.gif" },
  { name: "Wine", itemimg: "wine.gif" },

  // MEDICINES
  { name: "Brain Builder", itemimg: "" },
  { name: "Doolittle's Glyceride", itemimg: "doolittlesglyceride.gif" },
  { name: "Elixer of Persuassion", itemimg: "" },
  { name: "Elixer of Physical Prowess", itemimg: "elixerofphysicalprowess.gif" },
  { name: "Energizer", itemimg: "energizer.gif" },
  { name: "Famous Blood Pills", itemimg: "famousbloodpills.gif" },
  { name: "Lingham's Belladonna", itemimg: "linghamsbelladonna.gif" },
  { name: "Liquid of Awareness", itemimg: "" },
  { name: "Migraine Cure", itemimg: "migrainecure.gif" },
  { name: "Mind Marvel", itemimg: "" },
  { name: "Nerve Pills", itemimg: "nervepills.gif" },
  { name: "Nimm's Phosphourus Tincture", itemimg: "nimmsphosphoroustincture.gif" },
  { name: "Quinine", itemimg: "quinine.gif" },
  { name: "Revitalizer", itemimg: "" },
  { name: "Rheumatism Cure", itemimg: "rheumatismcure.gif" },
  { name: "Spirit of Camphor", itemimg: "spiritofcamphor.gif" },
  { name: "Tincture of Arnica", itemimg: "tinctureofarnica.gif" },
  { name: "Tonic of Increased Reflexes", itemimg: "" },
  { name: "Vendigrothian Elixer", itemimg: "vendigrothianelixer.gif" },
  { name: "Vivifier", itemimg: "" },

  // POTIONS
  { name: "Essence of Intellect", itemimg: "essenceofintellect.gif" },
  { name: "Fatigue Slower", itemimg: "fatigueslower.gif" },
  { name: "Greater Fatigue Restore", itemimg: "greaterfatiguerestore.gif" },
  { name: "Greater Healing", itemimg: "greaterhealing.gif" },
  { name: "Heal Lesser Wounds", itemimg: "heallesserwounds.gif" },
  { name: "Heal Poison", itemimg: "healpoison.gif" },
  { name: "Kalispi's Venom", itemimg: "kalispisvenom.gif" },
  { name: "Light Fatigue Restore", itemimg: "lightfatiguerestore.gif" },
  { name: "Liquid of Skin Thickening", itemimg: "liquidofskinthickening.gif" },
  { name: "Morgana's Tears", itemimg: "morganastears.gif" },
  { name: "Potion of Haste", itemimg: "potionofhaste.gif" },

  // TECHNOLOGICAL
  { name: "Ancient Gun Chassis", itemimg: "ancientgunchassis.gif" },
  { name: "Auto Loading Chamber", itemimg: "autoloadingchamber.gif" },
  { name: "Auto Skeleton Key", itemimg: "autoskeletonkey.gif" },
  { name: "Battery", itemimg: "battery.gif" },
  { name: "Bear Trap", itemimg: "beartrap.gif" },
  { name: "Black Powder", itemimg: "blackpowder.gif" },
  { name: "Broken Flintlock Pistol", itemimg: "brokenflintlockpistol.gif" },
  { name: "Bromide", itemimg: "bromide.gif" },
  { name: "Capacitor", itemimg: "capacitor.gif" },
  { name: "Charcoal", itemimg: "charcoal.gif" },
  { name: "Clock Parts", itemimg: "clockparts.gif" },
  { name: "Dwarven Ore", itemimg: "dwarvenore.gif" },
  { name: "Dwarven Steel", itemimg: "dwarvensteel.gif" },
  { name: "Dynamite", itemimg: "dynamite.gif" },
  { name: "Electrical Coil", itemimg: "electricalcoil.gif" },
  { name: "Electrical Harness", itemimg: "electricalharness.gif" },
  { name: "Electric Light", itemimg: "electriclight.gif" },
  { name: "Explosive Grenade", itemimg: "explosivegrenade.gif" },
  { name: "Filament", itemimg: "filament.gif" },
  { name: "Fine Hilt and Guard", itemimg: "finehiltandguard.gif" },
  { name: "Flash Grenade", itemimg: "" },
  { name: "Flow Specktrometer", itemimg: "flowspecktrometer.gif" },
  { name: "Fuel", itemimg: "fuel.gif" },
  { name: "Gun Chassis", itemimg: "gunchassis.gif" },
  { name: "Iron Ore", itemimg: "ironore.gif" },
  { name: "Kerosene", itemimg: "kerosene.gif" },
  { name: "Large Capacitor", itemimg: "largecapacitor.gif" },
  { name: "Large Spring", itemimg: "largespring.gif" },
  { name: "Lockpicks", itemimg: "lockpicks.gif" },
  { name: "Magnesium", itemimg: "magnesium.gif" },
  { name: "Medical Arachnid", itemimg: "medicalarachnid.gif" },
  { name: "Metal Casing", itemimg: "metalcasing.gif" },
  { name: "Metal Clamp", itemimg: "metalclamp.gif" },
  { name: "Metal Plates", itemimg: "metalplates.gif" },
  { name: "Metal Shavings", itemimg: "metalshavings.gif" },
  { name: "Molotov Cocktail", itemimg: "molotovcocktail.gif" },
  { name: "Music Box", itemimg: "musicbox.gif" },
  { name: "Nitroglycerin", itemimg: "nitroglycerin.gif" },
  { name: "Old Gears", itemimg: "oldgears.gif" },
  { name: "Pocket Watch Parts", itemimg: "pocketwatchparts.gif" },
  { name: "Potassium Chloride", itemimg: "potassiumchloride.gif" },
  { name: "Pure Ore", itemimg: "pureore.gif" },
  { name: "Revolver Chamber", itemimg: "revolverchamber.gif" },
  { name: "Revolver Parts", itemimg: "revolverparts.gif" },
  { name: "Saltpeter", itemimg: "saltpeter.gif" },
  { name: "Sheet Metal", itemimg: "sheetmetal.gif" },
  { name: "Small Electrical Parts", itemimg: "smallelectricalparts.gif" },
  { name: "Small Spring", itemimg: "smallspring.gif" },
  { name: "Small Steam Engine", itemimg: "smallsteamengine.gif" },
  { name: "Spike Trap", itemimg: "spiketrap.gif" },
  { name: "Spool of Heavy Wire", itemimg: "spoolofheavywire.gif" },
  { name: "Stearic Acid", itemimg: "stearicacid.gif" },
  { name: "Steel", itemimg: "steel.gif" },
  { name: "Stun Grenade", itemimg: "stungrenade.gif" },
  { name: "Tesla Coil", itemimg: "teslacoil.gif" },
  { name: "Thermometer", itemimg: "thermometer.gif" },
  { name: "Tom's Fertilizer", itemimg: "tomsfertilizer.gif" },
  { name: "Trap Springer", itemimg: "trapspringer.gif" },
  { name: "Unknown Chemical Compound", itemimg: "unknownchemicalcompound.gif" },
  { name: "Vendigrothian Sheet Metal", itemimg: "vendigrothiansheetmetal.gif" },

  // BOOKS
  { name: "Gilbert Bates' Journal", class: "books", itemimg: "Batesjournal.png", itemfolder: "1010 - Gilbert Bates' Journal" },
  { name: "The Legend of T'erre-d'-V'nt", class: "books", itemimg: "BookRed.png", itemfolder: "1020 - The Legend of T'erre-d'-V'nt" },
  { name: "Terms of Agreement", class: "books", itemimg: "Portfolio.png", itemfolder: "1030 - Dossier" },
  { name: "Joachim's Stillwater Book", class: "books", itemimg: "BookRed.png", itemfolder: "1050 - Joachim's Stillwater Book" },
  { name: "Liam Cameron's Journal", class: "books", itemimg: "BookRed.png", itemfolder: "1060 - Liam Cameron's Journal" },
  { name: "Divinations and Magicks For The Adept Wizard", class: "books", itemimg: "BookRed.png", itemfolder: "1070 - Divinations and Magicks For The Adept Wizard" },
  { name: "Panarii Pamphlet", class: "books", itemimg: "BookRed.png", itemfolder: "1090-1130 - Panarii Pamphlet" },
  { name: "Kraka-tur's Journal", class: "books", itemimg: "BookRed.png", itemfolder: "1140 - Kraka-tur's Journal" },
  { name: "Vendigroth Journal", class: "books", itemimg: "BookRed.png", itemfolder: "1150 - Vendigroth Journal" },
  { name: "Roan's Almanac of All Things Dwarven", class: "books", itemimg: "BookRed.png", itemfolder: "1160 - Roan's Almanac of All Things Dwarven" },
  { name: "Kerghan's Journal", class: "books", itemimg: "BookRed.png", itemfolder: "1170 - Kerghan's Journal" },
  { name: "The Pagan Gods of Arcanum", class: "books", itemimg: "BookRed.png", itemfolder: "1180 - The Pagan Gods of Arcanum" },
  { name: "Half-Ogre Laboratory Journal", class: "books", itemimg: "BookRed.png", itemfolder: "1190 - Half-Ogre Laboratory Journal" },
  { name: "The Curse of T'sen-Ang", class: "books", itemimg: "BookRed.png", itemfolder: "1200 - The Curse of T'sen-Ang" },
  { name: "Thorvald's Journal", class: "books", itemimg: "BookRed.png", itemfolder: "1210 - Thorvald's Journal" },
  { name: "How Nasrudin Defeated the Nefarious Arronax", class: "books", itemimg: "BookRed.png", itemfolder: "1220 - How Nasrudin Defeated the Nefarious Arronax" },
  { name: "Horror Among the Dark Elves", class: "books", itemimg: "BookRed.png", itemfolder: "1230 - Horror Among the Dark Elves" },
  { name: "Archaeon", class: "books", itemimg: "BookRed.png", itemfolder: "1240 - Archaeon" },
  { name: "Ashlag", class: "books", itemimg: "BookRed.png", itemfolder: "1250 - Ashlag" },
  { name: "Journal of Saint Mannox", class: "books", itemimg: "BookRed.png", itemfolder: "1260 - Journal of Saint Mannox" },
  { name: "Verses - There is only one step", class: "books", itemimg: "BookRed.png", itemfolder: "1270 - Verses - There is only one step" },
  { name: "Verses - The tie that binds", class: "books", itemimg: "BookRed.png", itemfolder: "1280 - Verses - The tie that binds" },
  { name: "Verses - Power", class: "books", itemimg: "BookRed.png", itemfolder: "1290 - Verses - Power" },
  { name: "Verses - All that comes before", class: "books", itemimg: "BookRed.png", itemfolder: "1300 - Verses - All that comes before" },
  { name: "The Hand", class: "books", itemimg: "BookRed.png", itemfolder: "1320 - The Hand" },
  { name: "Pamphlet - Come to Beautiful Roseborough", class: "books", itemimg: "BookRed.png", itemfolder: "1330 - Pamphlet - Come to Beautiful Roseborough" },
  { name: "Book of Durin's Truth", class: "books", itemimg: "BookRed.png", itemfolder: "1340 - Book of Durin's Truth" },
  { name: "The Poems of Eiloch", class: "books", itemimg: "BookRed.png", itemfolder: "1350 - The Poems of Eiloch" },
  { name: "Psychological Treatise On Intolerance", class: "books", itemimg: "BookRed.png", itemfolder: "1360 - Psychological Treatise On Intolerance" },
  { name: "A Response to - The Soot of the Gods", class: "books", itemimg: "BookRed.png", itemfolder: "1370 - A Response to - The Soot of the Gods" },
  { name: "Journal of Henry Dovern", class: "books", itemimg: "BookRed.png", itemfolder: "1380 - Journal of Henry Dovern" },
  { name: "The Nature of Archaeological Practice", class: "books", itemimg: "BookRed.png", itemfolder: "1390 - The Nature of Archaeological Practice" },
  { name: "The Horrors of Technology", class: "books", itemimg: "BookRed.png", itemfolder: "1400 - The Horrors of Technology" },
  { name: "The Orcish Question (Vol 1)", class: "books", itemimg: "BookRed.png", itemfolder: "1410 - The Orcish Question (Vol 1)" },
  { name: "The Orcish Question (Vol 2)", class: "books", itemimg: "BookRed.png", itemfolder: "1420 - The Orcish Question (Vol 2)" },
  { name: "The Life of Ashton Fernwilter", class: "books", itemimg: "BookRed.png", itemfolder: "1430 - The Life of Ashton Fernwilter" },
  { name: "Treatise on the Causes of Disease", class: "books", itemimg: "BookRed.png", itemfolder: "1440 - Treatise on the Causes of Disease" },
  { name: "Quirren's Poem", class: "books", itemimg: "BookRed.png", itemfolder: "1450 - Quirren's Poem" },
  { name: "Mastery of the Magickal Arts", class: "books", itemimg: "BookRed.png", itemfolder: "1460 - Mastery of the Magickal Arts" },
  { name: "Treatise on the Nature of Reality", class: "books", itemimg: "BookRed.png", itemfolder: "1470 - Treatise on the Nature of Reality" },
  { name: "The Gods Give Us Soot", class: "books", itemimg: "BookRed.png", itemfolder: "1480 - The Gods Give Us Soot" },
  { name: "Hunters Hunted", class: "books", itemimg: "BookRed.png", itemfolder: "1490 - Hunters Hunted" },
  { name: "History and Nature of Magick", class: "books", itemimg: "BookRed.png", itemfolder: "1500 - History and Nature of Magick" },
  { name: "The Great Work", class: "books", itemimg: "BookRed.png", itemfolder: "1510 - The Great Work" },
  { name: "Dread Armor", class: "books", itemimg: "BookRed.png", itemfolder: "1600 - Dread Armor" },
  { name: "History of the Isle of Despair", class: "books", itemimg: "BookRed.png", itemfolder: "1610 - History of the Isle of Despair" },

  // MANUALS
  { name: "Herbology", class: "books", itemimg: "BookBlue.png", itemfolder: "1520 - Herbology" },
  { name: "Chemistry", class: "books", itemimg: "BookBlue.png", itemfolder: "1530 - Chemistry" },
  { name: "Electricity", class: "books", itemimg: "BookBlue.png", itemfolder: "1540 - Electricity" },
  { name: "Explosives", class: "books", itemimg: "BookBlue.png", itemfolder: "1550 - Explosives" },
  { name: "Gunsmithy", class: "books", itemimg: "BookBlue.png", itemfolder: "1560 - Gunsmithy" },
  { name: "The Mechanical Discipline", class: "books", itemimg: "BookBlue.png", itemfolder: "1570 - The Mechanical Discipline" },
  { name: "Smithing", class: "books", itemimg: "BookBlue.png", itemfolder: "1580 - Smithing" },
  { name: "Therapeutics", class: "books", itemimg: "BookBlue.png", itemfolder: "1590 - Therapeutics" },

  // MAPS
  { name: "Map of Tarantian Sewers", class: "maps", image: "Textures/Maps/Map of Tarantian Sewers.png" },
  { name: "Map to Stringy Pete's Cove", class: "maps", image: "Textures/Maps/Map to Stringy Pete's Cove.png" },
  { name: "Map to the Place of Lost Voices", class: "maps", image: "Textures/Maps/Map to the Place of Voices.png" },
  { name: "Qintarra Map", class: "maps", image: "Textures/Maps/Qintarra Map.png" },
  { name: "Ristezze's Map", class: "maps", image: "Textures/Maps/Ristezze's Map.png" },
  { name: "Tollo's Map of Vendigroth", class: "maps", image: "Textures/Maps/Tollo's Map of Vendigroth.png" },
  { name: "Map to the Wheel Clan", class: "maps", image: "Textures/Maps/Map to the Wheel Clan.png" },

  // NEWSPAPERS
  { name: "Garringsburg Heist! Painting Stolen", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1020 - Garringsburg Heist! Painting Stolen.png" },
  { name: "Elven Tombs Discovered", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1030 - Elven Tombs Discovered.png" },
  { name: "Gilbert Bates Exposed as Fraud", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1050 - Gilbert Bates Exposed as Fraud.png" },
  { name: "Cedric Appleby found dead", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1060 - Cedric Appleby found dead.png" },
  { name: "Perriman Trainwreck", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1070 - Perriman Trainwreck.png" },
  { name: "Whytechurch Murderer Strikes", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1080 - Whytechurch Murderer Strikes.png" },
  { name: "Councilman urges war on Caladon", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1090 - Councilman urges war on Caladon.png" },
  { name: "Lawrence Brummond", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1110 - Lawrence Brummond.png" },
  { name: "Outlander Finds Stolen Painting_MASC", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1120 - Outlander Finds Stolen Painting_MASC.png" },
  { name: "Outlander Finds Stolen Painting_FEM", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1130 - Outlander Finds Stolen Painting_FEM.png" },
  { name: "IFS Zephyr Miracle Survivor Tells All MASC", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1150 - IFS Zephyr Miracle Survivor Tells All MASC.png" },
  { name: "IFS Zephyr Miracle Survivor Tells All FEM", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1160 - IFS Zephyr Miracle Survivor Tells All FEM.png" },
  { name: "IFS Zephyr Miracle Survivor Tells All MASC - LOW INT", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1170 - IFS Zephyr Miracle Survivor Tells All MASC - LOW INT.png" },
  { name: "IFS Zephyr Miracle Survivor Tells All FEM - LOW INT", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1180 - IFS Zephyr Miracle Survivor Tells All FEM - LOW INT.png" },
  { name: "NEWSPAPER_IFS Zephyr Missing", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1190 - NEWSPAPER_IFS Zephyr Missing.png" },
  { name: "NEWSPAPER_Payne Kills Demon", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1200 - NEWSPAPER_Payne Kills Demon.png" },
  { name: "Renford", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1210 - Renford.png" },
  { name: "Society Matron Murdered", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1220 - Society Matron Murdered.png" },
  { name: "Donn Throgg Still At Large", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1230 - Donn Throgg Still At Large.png" },
  { name: "Anarchist Laborers Take Over Factory", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1240 - Anarchist Laborers Take Over Factory.png" },
  { name: "Throgg Dead - Unknown Hero", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1260 - Throgg Dead - Unknown Hero.png" },
  { name: "Throgg Escapes", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/1270 - Throgg Escapes.png" },
  { name: "Technology protest claims 3 lives", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5000 - Technology protest claims 3 lives.png" },
  { name: "Flying machine rumors", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5010 - Flying machine rumors.png" },
  { name: "Council Passes Rodent Ordinance", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5020 - Council Passes Rodent Ordinance.png" },
  { name: "Strange Occurrences In Ashbury", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5030 - Strange Occurrences In Ashbury.png" },
  { name: "Criminal Science Marches Forward", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5040 - Criminal Science Marches Forward.png" },
  { name: "Mystery on the Hadrian", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5050 - Mystery on the Hadrian.png" },
  { name: "Castaways Rescued From Island", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5060 - Castaways Rescued From Island.png" },
  { name: "Pirate Ship Strikes Again", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5070 - Pirate Ship Strikes Again.png" },
  { name: "Noted Swordsmith Gives Lecture", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5080 - Noted Swordsmith Gives Lecture.png" },
  { name: "Professor To Try The Impossible!", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5090 - Professor To Try The Impossible!.png" },
  { name: "Noted Professor Dies Tragically", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5100 - Noted Professor Dies Tragically.png" },
  { name: "Local Woman Shows Green Thumb", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5110 - Local Woman Shows Green Thumb.png" },
  { name: "Petty Thefts Continue", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5120 - Petty Thefts Continue.png" },
  { name: "New Steel Plant Opens Doors", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5130 - New Steel Plant Opens Doors.png" },
  { name: "Pollution on the Rise", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5140 - Pollution on the Rise.png" },
  { name: "Franklin Payne Honored", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5150 - Franklin Payne Honored.png" },
  { name: "Physician Found Brutally Murdered", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5160 - Physician Found Brutally Murdered.png" },
  { name: "Councilman Babcock Speaks", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5170 - Councilman Babcock Speaks.png" },
  { name: "Special Edition", class: "tarantian", itemimg: "Newspaper.png", image: "Textures/Newspapers/5180 - Special Edition.png" },

  // THE VENDIGROTH TIMES
  { name: "Mage Threatens Vendigroth", class: "vendigroth", itemimg: "Newspaper2.png", image: "Textures/The Vendigroth Times/1280 - Mage Threatens Vendigroth.png" },
  { name: "Scanlan Factory Destroyed", class: "vendigroth", itemimg: "Newspaper2.png", image: "Textures/The Vendigroth Times/1290 - Scanlan Factory Destroyed.png" },
  { name: "Submersible 1", class: "vendigroth", itemimg: "Newspaper2.png", image: "Textures/The Vendigroth Times/1300 - Submersible 1.png" },
  { name: "Prof Hunley", class: "vendigroth", itemimg: "Newspaper2.png", image: "Textures/The Vendigroth Times/1310 - Prof Hunley.png" },

  // NOTES
  { name: "Raven letter from Renford", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1010 - Raven Letter from Renford.png" },
  { name: "Discrepancy in the translations of the Archaeon", itemimg: "Note.png", class: "notes" },
  { name: "Note to M'in Gorad from K'an Hua", itemimg: "Note.png", class: "notes", image: "Textures/Notes/1030 - Note to M'in Gorad from K'an Hua.png" },
  { name: "Safe Combination", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1040 - Safe Combination.png" },
  { name: "57 Mulligan Bone Alley", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1050 - 57 Mulligan Bone Alley.png" },
  { name: "Gentleman's Club List", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1060 - Gentleman's Club List.png" },
  { name: "Max Receipt", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1070 - Max Receipt.png" },
  { name: "Joachim’s Note to Virgil", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1080 - Joachim's Note to Virgil.png" },
  { name: "Prowling Master Note 1", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1100 - Prowling Master 1.png" },
  { name: "Prowling Master Note 2", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1110 - Prowling Master 2.png" },
  { name: "Prowling Master Note 3", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1120 - Prowling Master 3.png" },
  { name: "Prowling Master Note 3 Revelead", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1130 - Prowling Master 3 Revealed.png" },
  { name: "Note from Willenbecker Gang", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1140 - Note from Willenbecker Gang.png" },
  { name: "The IFS Zephyr has crashed", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1150 - William Radcliffe.png" },
  { name: "Wilhemina's Note to Jared", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1160 - Wilhemina's note to Jared.png" },
  { name: "Note for Mrs Regina Halster", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1170 - Note for Mrs Regina Halster.png" },
  { name: "Note to Loghaire from M'in Gorad", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1180 - to Loghaire from M'in.png" },
  { name: "Tyron's Note", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1190 - Tyron's Note.png" },
  { name: "Black Mountain Mines note of G.L.", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1200 - GL BMC.png" },
  { name: "Invitation to the Wellington Club", class: "notes", itemimg: "Note.png", image: "Textures/Notes/1210 - Invitation to the Wellington Club.png" },
  { name: "Elmer Burbottom's Letter to Mr. Carrington", itemimg: "Note.png", class: "notes", image: "Textures/Notes/1220 - Elmer Burbottom's Letter to Mr. Carrington.png" },

  // TELEGRAMS
  { name: "Ristezze's Telegraph", class: "telegraphs", itemimg: "Telegraph.png", image: "Textures/Telegrams/1020 - Ristezze's Telegram.png" },
  { name: "Benjamin Bates", class: "telegraphs", itemimg: "Telegraph.png", image: "Textures/Telegrams/1030 - Benjamin Bates.png" },
  { name: "Joachim Telegraph - Tarant", class: "telegraphs", itemimg: "Telegraph.png", image: "Textures/Telegrams/1040 - Joachim Telegraph - Tarant.png" },
  { name: "Prof Eakins", class: "telegraphs", itemimg: "Telegraph.png", image: "Textures/Telegrams/1050 - Prof Eakins.png" },

  // OTHERS



  // SCHEMATICS
  { name: "Schematics: Automaton" },
  { name: "Schematics: Wheel Clan Spectacles" },


/*
  // OTHERS

  { name: "Ancient Gun Chassis" },
  { name: "Dynamite" },
  { name: "Elephant Gun" },
  { name: "Envenomed Sword" },
  { name: "Harrow" }, // Not magick - Loghaire's axe
  { name: "Heavy Barbarian's Blade" },
  { name: "Levered Machine Gun" },
  { name: "Looking Glass Rifle" },
  { name: "Mechanical Dagger" },
  { name: "Power Axe" },
  { name: "Shovel" },


  // QUEST ITEMS
  { name: "...groth sprocket" },
  { name: "Amulet of N’Tala", tier: "magick" }, // Quest item
  { name: "Ancient Iron Drums" },
  { name: "Arabalah's Sacred Artifact" },
  { name: "Basic Machined Plate" },
  { name: "Bessie Toone's Boot" },
  { name: "Camera" },
  { name: "Crate of Ale" },
  { name: "Crystal Ball" },  
  { name: "Cynthia Boggs' Locket" },
  { name: "Fancy Ring" }, // Tarant sewers quest ring
  { name: "Funeral Stone" },
  { name: "Gem of Malachi Rench" },
  { name: "Gem of Water Purity" },
  { name: "Gift for Mrs. Regina Halster" },
  { name: "Gladys' Ring" },
  { name: "Golden Idol of Kree" },
  { name: "Great Ruby of K'alru" },
  { name: "Grunwalde's Poison" },
  { name: "J.T. Morgan's Master Locksmith Tools" },
  { name: "Kerghan and Persephone" },
  { name: "Lycanthrope Restorative" },
  { name: "Magickal trap" },
  { name: "Magnus' Bracelet" },
  { name: "Matchbook from Roseborough Inn" },
  { name: "Necklace of Queen K'na S'ea", tier: "magick" },
  { name: "Package for Jongle Dunne" },
  { name: "Preston Radcliffe's Passport" },
  { name: "Princess Aria's Amulet" },

  { name: "Silver Boot Bucket" },
  { name: "Skull from the Tomb of Nasrudin" },
  { name: "Small Statuette" },
  { name: "Statue of the Goddess Geshtianna" },
  { name: "Stillwater Giant Pelt" },
  { name: "Stringy Pete's Treasure" },
  { name: "The Skulls of the Ren'ar Siamese Twins" },
  { name: "Trevor Lynwood's Camera" },
  { name: "Wheel Clan Spectacles" },
  { name: "White Scarf" },

  // THIEVES UNDERGROUND BOUNTIES - TARANT (14/14)
  { name: "Cassie's Jewellery" },
  { name: "Derian Ka Sword" },
  { name: "Enchanted Looking Glass" },
  { name: "Flawless Dwarven Rubies" },
  { name: "Heron Device" },
  { name: "Jewel Of Hebe" },
  { name: "Lethe Wyvern Venom" },
  { name: "Lucky Medallion" },
  { name: "Madam Lil's Music Box" },
  { name: "Napha Water" },
  { name: "Plans For Schreck's Multi-barrel Pistol" },
  { name: "Potion Of Dark Power" },
  { name: "Ring Of Virility" },
  { name: "Will-O-The-Wisp Essence" },

  // THIEVES UNDERGROUND BOUNTIES - CALADON (4/7)
  // Missing: Caladon Crusading Armor
  { name: "Chest of Gold" },
  { name: "Magick Necklace", tier: "magick" },
  { name: "Post Bound For Tarant" },
  { name: "Ryan Marshall's Police Record" },
  // Missing: Pocket watch
  // Missing: Staff of Restoration

  // KEYS
  { name: "Bates Mausoleum Key" },
  { name: "Dragon Pool Key 2" },
  { name: "Innkeeper's Key, Dernholm" },
  { name: "Magick Shoppe Key. Tarant" },
  { name: "Key for Stillwater Giant Case" },
  { name: "Key to Garret Almstead's Trunk" },
  { name: "Key to Lloyd Gurloes’ backroom" },
  { name: "Key to Ristezze’s Bedroom" },
  { name: "Key to the Back Room in 57 Mulligan Bone" },
  { name: "Key to the factory" },
  { name: "Key to the Gates of the Isle of Despair" },
  { name: "Key to the Shrouded Hills Bridge Gate" },
  { name: "Key to the Warehouse of the Small" },
  { name: "Key to Thorvald's Chest" },
  { name: "Key to Thorvald's House" },
  { name: "Ristezze's File Cabinet Key" },
  { name: "Roseborough Inn Key" },
  { name: "Roseborough Inn Room Key" },
  { name: "Shrouded Hills Bank Key" },
  { name: "Vernon's key" },

    // MAGICK
  { name: "Arcane Axe", tier: "magick" },
  { name: "Arcane Bow", tier: "magick" },
  { name: "Arcane Gauntlets", tier: "magick" },
  { name: "Arcane Ring", tier: "magick" },
  { name: "Arcane Robes", tier: "magick" },
  { name: "Arcane Staff", tier: "magick" },

  { name: "Ashen Robes", tier: "magick" },
  { name: "Blessed Bow", tier: "magick" },
  { name: "Charmed Ring", tier: "magick" },
  { name: "Charming Medallion", tier: "magick" },
  { name: "Dagger of Speed", tier: "magick" },
  { name: "Divining Staff", tier: "magick" },
  { name: "Ellumyn's Bow", tier: "magick" },
  { name: "Elven Hunter Bow", tier: "magick"  },
  { name: "Enchanted Gown", tier: "magick" },
  { name: "Infernal Hammer", tier: "magick" },
  { name: "Mage’s Dagger", tier: "magick" },
  { name: "Mage's Staff", tier: "magick" },
  { name: "Magick Bow", tier: "magick" },
  { name: "Magick Ring", tier: "magick" },
  { name: "Magick Robes", tier: "magick" },
  { name: "Mastery Medallion of Meta", tier: "magick" },
  { name: "Mastery Medallion of Water", tier: "magick" },
  { name: "Medallion of Beauty", tier: "magick" },
  { name: "Mithril Chainmail", tier: "magick" },
  { name: "Mystic Traveler's Cloak", tier: "magick" },
  { name: "Robe of Fire Protection", tier: "magick" },
  { name: "Screaming Scimtar", tier: "magick" },
  { name: "Screaming Shield", tier: "magick" },
  { name: "Shaman's Staff", tier: "magick" },
  { name: "Shocking Dagger", tier: "magick" },
  { name: "Staff of Healing", tier: "magick" },
  { name: "Stillwater Blade", tier: "magick" },
  { name: "Sword of Baltar", tier: "magick" },
  { name: "Witch's Dagger", tier: "magick" },

  // MAGICK - SCROLL
  { name: "Scroll of Bonds of Magic", tier: "magick" },
  { name: "Scroll of Call Air Elemental", tier: "magick" },
  { name: "Scroll of Call Earth Elemental", tier: "magick" },
  { name: "Scroll of Call Water Elemental", tier: "magick" },
  { name: "Scroll of Disarm", tier: "magick" },
  { name: "Scroll of Disperse Magick", tier: "magick" },
  { name: "Scroll of Flesh to Stone", tier: "magick" },
  { name: "Scroll of Major Healing", tier: "magick" },
  { name: "Scroll of Polymorph", tier: "magick" },
  { name: "Scroll of Sense Invisible/Traps", tier: "magick" },
  { name: "Scroll of Squall of Ice", tier: "magick" },
  { name: "Scroll of Summon Undead", tier: "magick" },
  { name: "Scroll of Teleportation", tier: "magick" },

  // HEXED
  { name: "Baneful Gauntlets", tier: "hexed" },
  { name: "Blade of Vicious Haste", tier: "hexed" },
  { name: "Boots of the Dark Toll", tier: "hexed" },

  { name: "Helmet of Yzar's Cost", tier: "hexed" },
  { name: "Hero's Weakness Barbarian Armor", tier: "hexed" },
  { name: "Hexed Dagger", tier: "hexed" },
  { name: "Hexed Leather Armour", tier: "hexed" },
  { name: "Mace of the Damned", tier: "hexed" },
  { name: "Serpentine Necklace", tier: "hexed" },
  { name: "Shadow Hand Dagger", tier: "hexed" },

*/
];
