const ArcanumShopInventoryData = {
	"General Store (Rural)": [
		{ name: "Arrow", chance: 100 },
		{ name: "Charcoal", chance: 100 },
		{ name: "Saltpeter", chance: 100 },
		{ name: "Heal Poison", chance: 100 },
		{ name: "Bandages", chance: 100 },
		{ name: "Bullet", chance: 100 },
		{ name: "Battery", chance: 80 },
		{ name: "Liquid Soap", chance: 80 },
		{ name: "Tom's Fertilizer", chance: 80 },
		{ name: "Dwarven Snuff", chance: 80 },
		{ name: "Light Fatigue Restore", chance: 70 },
		{ name: "Greater Fatigue Restore", chance: 70 },
		{ name: "Greater Healing", chance: 70 },
		{ name: "Suede Jacket", chance: 70 },
		{ name: "Earl Grey Tea", chance: 60 },
		{ name: "Sweet Cakes", chance: 60 },
		{ name: "Healing Salve", chance: 50 },
		{ name: "Fatigue Restorer", chance: 50 },
		{ name: "Heal Lesser Wounds", chance: 50 },
		{ name: "Dagger", chance: 40 },
		{ name: "Sword", chance: 40 },
		{ name: "Old Revolver", chance: 40 },
		{ name: "Old Flintlock Pistol", chance: 40 },
		{ name: "Short Bow", chance: 40 },
		{ name: "Staff", chance: 40 },
		{ name: "CK Sugar", chance: 40 },
		{ name: "Migraine Cure", chance: 40 },
		{ name: "Wooden Shield", chance: 40 },
		{ name: "Helmet", chance: 40 },
		{ name: "Worn Shoes", chance: 40 },
		{ name: "Worn Boots", chance: 40 },
		{ name: "Worn Ladies Boots", chance: 40 },
		{ name: "Tincture of Arnica", chance: 30 },
		{ name: "Leather Armour", chance: 30 },
		{ name: "Rustic Finery", chance: 30 },
		{ name: "Rustic Dress", chance: 30 },
		{ name: "Leather Gloves", chance: 30 },
		{ name: "Lantern", chance: 30 },
		{ name: "Metal Can", chance: 25 },
		{ name: "Rheumatism Cure", chance: 25 },
		{ name: "Eye Glasses", chance: 25 },
		{ name: "Coca Leaves", chance: 25 },
		{ name: "Big Chief Snake Oil", chance: 25 },
		{ name: "Brewer's Yeast", chance: 25 },
		{ name: "Monroe's Cleaner", chance: 25 },
		{ name: "Sulphur Pills", chance: 25 },
		{ name: "Wine", chance: 25 },
		{ name: "Varham's Aqua Vitae", chance: 25 },
		{ name: "Morning Star Perfume", chance: 25 },
		{ name: "Dragon Cologne", chance: 25 },
		{ name: "Lingham's Belladonna", chance: 25 },
		{ name: "Famous Blood Pills", chance: 25 },
		{ name: "Doolittle's Glyceride", chance: 25 },
		{ name: "Nerve Pills", chance: 25 },
		{ name: "Nimm's Phosphorous Tincture", chance: 25 },
		{ name: "Quinine", chance: 25 },
		{ name: "Spirit of Camphor", chance: 25 },
		{ name: "Water", chance: 25 },
		{ name: "Bread", chance: 25 },
		{ name: "Black Powder", chance: 25 },
		{ name: "Thermometer", chance: 25 },
		{ name: "Shovel", chance: 25 },
		{ name: "Scroll of Divine Magic", chance: 20 },
		{ name: "Scroll of Resurrect", chance: 20 },
		{ name: "Heavy Wool Clothes", chance: 20 },
		{ name: "Jacket", chance: 20 },
		{ name: "Robes", chance: 20 },
		{ name: "Key Ring", chance: 20 },
		{ name: "Scroll of Exiting", chance: 10 },
		{ name: "Absinthe", chance: 10 },
		{ name: "Small Heavy Wool Clothes", chance: 10 },
		{ name: "Small Suede Jacket", chance: 10 },
		{ name: "Small Jacket", chance: 10 },
		{ name: "Small Leather Armour", chance: 10 },
		{ name: "Small Rustic Finery", chance: 10 },
		{ name: "Boomerang", chance: 10 },
		{ name: "Small Robes", chance: 5 },
	],
	"General Store (City)": [
		{ name: "Arrow", chance: 100 },
		{ name: "Heal Poison", chance: 100 },
		{ name: "Bandages", chance: 100 },
		{ name: "Heal Lesser Wounds", chance: 100 },
		{ name: "Earl Grey Tea", chance: 100 },
		{ name: "Dwarven Snuff", chance: 100 },
		{ name: "Key Ring", chance: 100 },
		{ name: "Bullet", chance: 100 },
		{ name: "Light Fatigue Restore", chance: 90 },
		{ name: "Greater Fatigue Restore", chance: 90 },
		{ name: "Greater Healing", chance: 90 },
		{ name: "Dagger", chance: 80 },
		{ name: "Sword", chance: 80 },
		{ name: "Old Revolver", chance: 80 },
		{ name: "Old Flintlock Pistol", chance: 80 },
		{ name: "Short Bow", chance: 80 },
		{ name: "Staff", chance: 80 },
		{ name: "Liquid Soap", chance: 80 },
		{ name: "Migraine Cure", chance: 80 },
		{ name: "Wooden Shield", chance: 80 },
		{ name: "Helmet", chance: 80 },
		{ name: "Worn Shoes", chance: 80 },
		{ name: "Worn Boots", chance: 80 },
		{ name: "Worn Ladies Boots", chance: 80 },
		{ name: "Suede Jacket", chance: 70 },
		{ name: "Leather Armour", chance: 60 },
		{ name: "Rustic Finery", chance: 60 },
		{ name: "Rustic Dress", chance: 60 },
		{ name: "Leather Gloves", chance: 60 },
		{ name: "Lantern", chance: 60 },
		{ name: "Sweet Cakes", chance: 60 },
		{ name: "Healing Salve", chance: 50 },
		{ name: "Fatigue Restorer", chance: 50 },
		{ name: "Battery", chance: 50 },
		{ name: "Tincture of Arnica", chance: 50 },
		{ name: "Rheumatism Cure", chance: 50 },
		{ name: "Coca Leaves", chance: 50 },
		{ name: "Big Chief Snake Oil", chance: 50 },
		{ name: "Brewer's Yeast", chance: 50 },
		{ name: "Monroe's Cleaner", chance: 50 },
		{ name: "Wine", chance: 50 },
		{ name: "Varham's Aqua Vitae", chance: 50 },
		{ name: "Morning Star Perfume", chance: 50 },
		{ name: "Dragon Cologne", chance: 50 },
		{ name: "Lingham's Belladonna", chance: 50 },
		{ name: "Famous Blood Pills", chance: 50 },
		{ name: "Doolittle's Glyceride", chance: 50 },
		{ name: "Quinine", chance: 50 },
		{ name: "Spirit of Camphor", chance: 50 },
		{ name: "Water", chance: 50 },
		{ name: "Bread", chance: 50 },
		{ name: "Black Powder", chance: 50 },
		{ name: "Thermometer", chance: 50 },
		{ name: "Shovel", chance: 50 },
		{ name: "Tom's Fertilizer", chance: 40 },
		{ name: "CK Sugar", chance: 40 },
		{ name: "Heavy Wool Clothes", chance: 40 },
		{ name: "Jacket", chance: 40 },
		{ name: "Robes", chance: 40 },
		{ name: "Scroll of Exiting", chance: 30 },
		{ name: "Scroll of Divine Magic", chance: 20 },
		{ name: "Scroll of Resurrect", chance: 20 },
		{ name: "Small Heavy Wool Clothes", chance: 20 },
		{ name: "Small Suede Jacket", chance: 20 },
		{ name: "Small Jacket", chance: 20 },
		{ name: "Small Leather Armour", chance: 20 },
		{ name: "Kerosene", chance: 20 },
		{ name: "Small Rustic Finery", chance: 10 },
		{ name: "Small Robes", chance: 10 },
		{ name: "Boomerang", chance: 5 },
	],
	"Elven Trader": [
		{ name: "Scroll of Exiting", chance: 100 },
		{ name: "Heal Lesser Wounds", chance: 100 },
		{ name: "Elven Spring Water", chance: 100 },
		{ name: "Light Fatigue Restore", chance: 100 },
		{ name: "Bullet", chance: 100 },
		{ name: "Arrow", chance: 100 },
		{ name: "Bandages", chance: 100 },
		{ name: "Wooden Ring", chance: 20 },
		{ name: "Fatigue Slower", chance: 50 },
		{ name: "Potion of Haste", chance: 50 },
		{ name: "Mage's Dagger", chance: 50 },
		{ name: "Dagger of Speed", chance: 50 },
		{ name: "Short Sword", chance: 50 },
		{ name: "Scimitar", chance: 50 },
		{ name: "Enchanted Sword", chance: 50 },
		{ name: "Bow", chance: 70 },
		{ name: "Long Bow", chance: 50 },
		{ name: "Elven Hunter's Bow", chance: 80 },
		{ name: "Staff of Healing", chance: 60 },
		{ name: "Mage's Staff", chance: 40 },
		{ name: "Elven Boots", chance: 80 },
		{ name: "Fated Ring", chance: 50 },
		{ name: "Dorian Amulet", chance: 50 },
		{ name: "Oiled Thieves Leather", chance: 60 },
		{ name: "Small Oiled Thieves Leather", chance: 60 },
		{ name: "Elven Chainmail", chance: 80 },
		{ name: "Shadowing Robes", chance: 40 },
	],
	"Herbalist": [
		{ name: "Fatigue Restorer", chance: 50 },
		{ name: "Restore Life", chance: 50 },
		{ name: "Healing Salve", chance: 50 },
		{ name: "Tincture of Arnica", chance: 50 },
		{ name: "Rheumatism Cure", chance: 50 },
		{ name: "Tom's Fertilizer", chance: 40 },
		{ name: "Migraine Cure", chance: 40 },
		{ name: "Saltpeter", chance: 66 },
		{ name: "Coca Leaves", chance: 66 },
		{ name: "Ginka Root", chance: 66 },
		{ name: "Kadura Stem", chance: 66 },
		{ name: "Witchbane", chance: 66 },
		{ name: "Poppy Flowers", chance: 66 },
		{ name: "Big Chief Snake Oil", chance: 66 },
		{ name: "Tobacco Leaves", chance: 66 },
		{ name: "Venom", chance: 66 },
		{ name: "Brewer's Yeast", chance: 66 },
		{ name: "Pete's Carbolic Acid", chance: 66 },
		{ name: "Electrolyte Solution", chance: 66 },
		{ name: "Mushrooms", chance: 66 },
		{ name: "Sulphur Pills", chance: 66 },
		{ name: "Wine", chance: 66 },
		{ name: "Varham's Aqua Vitae", chance: 66 },
		{ name: "Morning Star Perfume", chance: 66 },
		{ name: "Dragon Cologne", chance: 66 },
		{ name: "Lingham's Belladonna", chance: 66 },
		{ name: "Famous Blood Pills", chance: 66 },
		{ name: "Doolittle's Glyceride", chance: 66 },
		{ name: "Nerve Pills", chance: 66 },
		{ name: "Nimm's Phosphorous Tincture", chance: 66 },
		{ name: "Quinine", chance: 66 },
		{ name: "Spirit of Camphor", chance: 66 },
		{ name: "Water", chance: 66 },
		{ name: "Bread", chance: 66 },
		{ name: "Bandages", chance: 100 },
		{ name: "Schematic: Fortifier", chance: 20 },
		{ name: "Schematic: Miracle Cure", chance: 20 },
		{ name: "Schematic: Invigorator", chance: 20 },
		{ name: "Schematic: Fuel", chance: 20 },
	],
	"Junk Dealer": [
		{ name: "Rag", chance: 80 },
		{ name: "Boat Rigging", chance: 20 },
		{ name: "Metal Can", chance: 85 },
		{ name: "Oak Axe Handle", chance: 20 },
		{ name: "Engine Muffler", chance: 50 },
		{ name: "Metal Casing", chance: 50 },
		{ name: "Broken Flintlock Pistol", chance: 70 },
		{ name: "Revolver Parts", chance: 70 },
		{ name: "Metal Clamp", chance: 70 },
		{ name: "Large Gears", chance: 70 },
		{ name: "Large Spring", chance: 70 },
		{ name: "Rusty Dagger", chance: 40 },
		{ name: "Small Spring", chance: 70 },
		{ name: "Railroad Spike", chance: 70 },
		{ name: "Pocket Watch Parts", chance: 70 },
		{ name: "Music Box", chance: 70 },
		{ name: "Old Gears", chance: 70 },
		{ name: "Metal Plates", chance: 70 },
		{ name: "Gun Chassis", chance: 70 },
		{ name: "Clock Parts", chance: 70 },
		{ name: "Rusty Sword", chance: 40 },
		{ name: "Old Flintlock Pistol", chance: 40 },
		{ name: "Small Metal Tube", chance: 70 },
		{ name: "Leather Straps", chance: 70 },
		{ name: "Old Revolver", chance: 40 },
		{ name: "Metal Shavings", chance: 70 },
		{ name: "Iron Ore", chance: 70 },
		{ name: "Sheet Metal", chance: 70 },
		{ name: "Steel", chance: 70 },
		{ name: "Shovel", chance: 70 },
		{ name: "Coal", chance: 70 },
		{ name: "Rusty Axe", chance: 40 },
		{ name: "Rusty Mace", chance: 40 },
		{ name: "Rusty Hammer", chance: 40 },
		{ name: "Mnura Coin", chance: 40 },
	],
	"Inventor": [
		{ name: "Minute Steam Works", chance: 10 },
		{ name: "Small Steam Engine", chance: 10 },
		{ name: "Corrosive Acid", chance: 25 },
		{ name: "Kerosene", chance: 25 },
		{ name: "Nitroglycerin", chance: 25 },
		{ name: "Potassium Chloride", chance: 25 },
		{ name: "Large Pipe", chance: 80 },
		{ name: "Looking Glass", chance: 80 },
		{ name: "Liquid Soap", chance: 80 },
		{ name: "Metal Can", chance: 75 },
		{ name: "Bromide", chance: 75 },
		{ name: "Electrical Coil", chance: 75 },
		{ name: "Stearic Acid", chance: 75 },
		{ name: "Metal Casing", chance: 50 },
		{ name: "Small Electrical Parts", chance: 75 },
		{ name: "Thermometer", chance: 75 },
		{ name: "Saltpeter", chance: 75 },
		{ name: "Charcoal", chance: 75 },
		{ name: "Pocket Watch Parts", chance: 90 },
		{ name: "Metal Plates", chance: 90 },
		{ name: "Capacitor", chance: 90 },
		{ name: "Electrical Harness", chance: 90 },
		{ name: "Filament", chance: 90 },
		{ name: "Large Capacitor", chance: 90 },
		{ name: "Tesla Coil", chance: 30 },
		{ name: "Magnesium", chance: 90 },
		{ name: "Clock Parts", chance: 90 },
		{ name: "Spool of Heavy Wire", chance: 90 },
		{ name: "Eye Glasses", chance: 70 },
		{ name: "Battery", chance: 100 },
		{ name: "Fuel", chance: 100 },
		{ name: "Schematic: Lemon and Potato Charges", chance: 10 },
		{ name: "Schematic: Flow Disruptor", chance: 10 },
		{ name: "Schematic: Tesla Gun", chance: 10 },
		{ name: "Schematic: Medical Arachnid", chance: 10 },
		{ name: "Schematic: Goggled Helmet", chance: 10 },
	],
	"Tailor (City)": [
		{ name: "Nice Suit", chance: 90 },
		{ name: "Small Nice Suit", chance: 90 },
		{ name: "Large Nice Suit", chance: 20 },
		{ name: "Smoking Jacket", chance: 90 },
		{ name: "Small Smoking Jacket", chance: 90 },
		{ name: "Servants Clothes", chance: 70 },
		{ name: "Small Manservants Clothes", chance: 60 },
		{ name: "Large Manservants Uniform", chance: 90 },
		{ name: "Servant's Dress", chance: 80 },
		{ name: "Plain Dress", chance: 80 },
		{ name: "Small Robes", chance: 10 },
		{ name: "Robes", chance: 20 },
		{ name: "Magick Robes", chance: 33 },
		{ name: "Leather Gloves", chance: 80 },
		{ name: "Shoes", chance: 90 },
		{ name: "Ladies Fancy Boots", chance: 90 },
		{ name: "Top Hat", chance: 90 },
		{ name: "Fancy Ring", chance: 70 },
		{ name: "Decent Gold Ring", chance: 70 },
		{ name: "Medallion", chance: 70 },
		{ name: "Morning Star Perfume", chance: 80 },
		{ name: "Dragon Cologne", chance: 80 },
		{ name: "Pocket Watch", chance: 80 },
		{ name: "Large Heavy Wool Clothes", chance: 20 },
		{ name: "Heavy Rags", chance: 20 },
	],
	"Tailor (Rural)": [
		{ name: "Heavy Wool Clothes", chance: 90 },
		{ name: "Wool Jacket", chance: 80 },
		{ name: "Small Wool Jacket", chance: 20 },
		{ name: "Jacket", chance: 90 },
		{ name: "Small Jacket", chance: 20 },
		{ name: "Rustic Finery", chance: 90 },
		{ name: "Small Rustic Finery", chance: 20 },
		{ name: "Large Rustic Finery", chance: 10 },
		{ name: "Rustic Dress", chance: 90 },
		{ name: "Small Robes", chance: 20 },
		{ name: "Robes", chance: 70 },
		{ name: "Worn Shoes", chance: 80 },
		{ name: "Worn Boots", chance: 80 },
		{ name: "Worn Ladies Boots", chance: 80 },
		{ name: "Decent Gold Ring", chance: 80 },
		{ name: "Medallion", chance: 80 },
		{ name: "Large Heavy Wool Clothes", chance: 10 },
	],
	"Smith (Rural)": [
		{ name: "Arrow", chance: 100 },
		{ name: "Bullet", chance: 100 },
		{ name: "Dagger", chance: 80 },
		{ name: "Fine Steel Dagger", chance: 60 },
		{ name: "Dagger of Speed", chance: 10 },
		{ name: "Sword", chance: 80 },
		{ name: "Quality Sword", chance: 60 },
		{ name: "Falchion", chance: 30 },
		{ name: "Sword of Defense", chance: 10 },
		{ name: "Enchanted Sword", chance: 10 },
		{ name: "Axe", chance: 80 },
		{ name: "Axe of Strength", chance: 10 },
		{ name: "Mace", chance: 80 },
		{ name: "Hammer", chance: 80 },
		{ name: "Crushing Hammer", chance: 10 },
		{ name: "Inferno Hammer", chance: 10 },
		{ name: "Flintlock Pistol", chance: 80 },
		{ name: "Broadsword", chance: 80 },
		{ name: "Oak Axe Handle", chance: 10 },
		{ name: "Bow", chance: 80 },
		{ name: "Hunting Rifle", chance: 80 },
		{ name: "Leather Armour", chance: 80 },
		{ name: "Small Leather Armour", chance: 15 },
		{ name: "Oiled Thieves Leather", chance: 10 },
		{ name: "Studded Leather", chance: 80 },
		{ name: "Small Studded Leather", chance: 15 },
		{ name: "Large Studded Leather", chance: 5 },
		{ name: "Chainmail", chance: 70 },
		{ name: "Small Chainmail", chance: 10 },
		{ name: "Dwarven Chainmail", chance: 2 },
		{ name: "Dread Armour", chance: 70 },
		{ name: "Battered Wooden Shield", chance: 70 },
		{ name: "Dented Iron Shield", chance: 70 },
		{ name: "Helmet", chance: 80 },
		{ name: "Fine Helmet", chance: 20 },
		{ name: "Gauntlets", chance: 70 },
		{ name: "Leather Gloves", chance: 90 },
		{ name: "Chain Gloves", chance: 70 },
		{ name: "Copper Ring", chance: 90 },
		{ name: "Leather Straps", chance: 80 },
		{ name: "Metal Shavings", chance: 80 },
		{ name: "Fine Hilt and Guard", chance: 80 },
		{ name: "Iron Ore", chance: 80 },
		{ name: "Bladed Boomerang", chance: 5 },
	],
	"Smith (Quality)": [
		{ name: "Arrow", chance: 100 },
		{ name: "Bullet", chance: 100 },
		{ name: "Great Helm", chance: 100 },
		{ name: "Schematic: Mechanical Dagger", chance: 10 },
		{ name: "Schematic: Envenomed Axe", chance: 10 },
		{ name: "Fine Steel Dagger", chance: 70 },
		{ name: "Throwing Dagger", chance: 70 },
		{ name: "Quality Sword", chance: 70 },
		{ name: "Caladon Elite Sword", chance: 70 },
		{ name: "Rapier", chance: 70 },
		{ name: "Short Sword", chance: 70 },
		{ name: "Scimitar", chance: 70 },
		{ name: "Katana", chance: 70 },
		{ name: "Falchion", chance: 70 },
		{ name: "Schematic: Pyrotechnic Axe", chance: 5 },
		{ name: "Axe", chance: 80 },
		{ name: "Quality Axe", chance: 60 },
		{ name: "Mace", chance: 50 },
		{ name: "Quality Mace", chance: 50 },
		{ name: "Hammer", chance: 50 },
		{ name: "Quality Hammer", chance: 50 },
		{ name: "Quality Broadsword", chance: 50 },
		{ name: "Claymore", chance: 70 },
		{ name: "Flamberge", chance: 70 },
		{ name: "Studded Leather", chance: 60 },
		{ name: "Small Studded Leather", chance: 10 },
		{ name: "Large Studded Leather", chance: 5 },
		{ name: "Chainmail", chance: 60 },
		{ name: "Oiled Chainmail", chance: 60 },
		{ name: "Small Oiled Chainmail", chance: 10 },
		{ name: "Small Chainmail", chance: 10 },
		{ name: "Dwarven Chainmail", chance: 5 },
		{ name: "Basic Platemail", chance: 70 },
		{ name: "Bronzed Plate", chance: 50 },
		{ name: "Quality Iron Shield", chance: 60 },
		{ name: "Kite Shield", chance: 70 },
		{ name: "Helmet", chance: 70 },
		{ name: "Fine Helmet", chance: 70 },
		{ name: "Pig Face Basset", chance: 70 },
		{ name: "Gauntlets", chance: 70 },
		{ name: "War Gauntlets", chance: 70 },
		{ name: "Chain Gloves", chance: 70 },
		{ name: "Metal Boots", chance: 70 },
		{ name: "Fine Stout Boots", chance: 70 },
		{ name: "Copper Ring", chance: 70 },
		{ name: "Fine Hilt and Guard", chance: 70 },
		{ name: "Iron Ore", chance: 70 },
		{ name: "Sheet Metal", chance: 70 },
		{ name: "Bladed Boomerang", chance: 80 },
		{ name: "Oiled Thieves Leather", chance: 10 },
		{ name: "Large Wool Jacket", chance: 10 },
		{ name: "Large Leather Armour", chance: 10 },
		{ name: "Schematic: Charged Sword", chance: 5 },
		{ name: "Schematic: Electro Armour (Medium)", chance: 5 },
		{ name: "Schematic: Blade Launcher", chance: 5 },
		{ name: "Schematic: Envenomed Sword", chance: 5 },
		{ name: "Schematic: Miner's Helmet", chance: 5 },
		{ name: "Schematic: Compound Bow", chance: 8 },
		{ name: "Schematic: Envenomed Bow", chance: 5 },
	],
	"Smith (Magical)": [
		{ name: "Arrow", chance: 100 },
		{ name: "Mithril Chainmail", chance: 1 },
		{ name: "Fine Steel Dagger", chance: 70 },
		{ name: "Mage's Dagger", chance: 70 },
		{ name: "Dagger of Speed", chance: 70 },
		{ name: "Sword", chance: 70 },
		{ name: "Quality Sword", chance: 70 },
		{ name: "Caladon Elite Sword", chance: 70 },
		{ name: "Scimitar", chance: 70 },
		{ name: "Sword of Defense", chance: 70 },
		{ name: "Enchanted Sword", chance: 20 },
		{ name: "Stillwater Blade", chance: 70 },
		{ name: "Quality Axe", chance: 70 },
		{ name: "Reaper's Axe", chance: 20 },
		{ name: "Axe of Strength", chance: 70 },
		{ name: "Quality Mace", chance: 70 },
		{ name: "Quality Hammer", chance: 70 },
		{ name: "Crushing Hammer", chance: 70 },
		{ name: "Inferno Hammer", chance: 20 },
		{ name: "Broadsword", chance: 70 },
		{ name: "Quality Broadsword", chance: 70 },
		{ name: "Sword of Air", chance: 70 },
		{ name: "Sword of Sickness", chance: 20 },
		{ name: "Elven Hunter's Bow", chance: 20 },
		{ name: "Bow of Terror", chance: 20 },
		{ name: "Studded Leather", chance: 70 },
		{ name: "Small Studded Leather", chance: 10 },
		{ name: "Large Studded Leather", chance: 5 },
		{ name: "Dragon Skin Leather", chance: 80 },
		{ name: "Chainmail", chance: 50 },
		{ name: "Small Chainmail", chance: 10 },
		{ name: "Dwarven Chainmail", chance: 5 },
		{ name: "Elven Chainmail", chance: 60 },
		{ name: "Gnomish Chainmail", chance: 30 },
		{ name: "Basic Platemail", chance: 50 },
		{ name: "Minute Platemail of Regeneration", chance: 50 },
		{ name: "Dread Armour", chance: 80 },
		{ name: "Quality Iron Shield", chance: 70 },
		{ name: "Shield of Force", chance: 80 },
		{ name: "Shadow Shield", chance: 70 },
		{ name: "Fine Helmet", chance: 70 },
		{ name: "Helm of Light", chance: 80 },
		{ name: "Geleam's Helm", chance: 20 },
		{ name: "Gauntlets", chance: 60 },
		{ name: "War Gauntlets", chance: 60 },
		{ name: "Chain Gloves", chance: 60 },
		{ name: "Light-Fingered Gauntlets", chance: 80 },
		{ name: "Elven Boots", chance: 60 },
		{ name: "Enchanted War Boots", chance: 70 },
		{ name: "Chakram", chance: 80 },
		{ name: "Serrated Chakram", chance: 80 },
	],
	"Smith (Dwarven)": [
		{ name: "Arrow", chance: 100 },
		{ name: "Schematic: Pyrotechnic Axe", chance: 10 },
		{ name: "Schematic: Charged Sword", chance: 5 },
		{ name: "Schematic: Electro Armour (Medium)", chance: 5 },
		{ name: "Schematic: Blade Launcher", chance: 5 },
		{ name: "Schematic: Envenomed Sword", chance: 5 },
		{ name: "Battery", chance: 80 },
		{ name: "Schematic: Miner's Helmet", chance: 5 },
		{ name: "Schematic: Compound Bow", chance: 8 },
		{ name: "Schematic: Envenomed Bow", chance: 5 },
		{ name: "Dwarven Steel", chance: 85 },
		{ name: "Great Helm", chance: 100 },
		{ name: "Fine Steel Dagger", chance: 90 },
		{ name: "Quality Sword", chance: 90 },
		{ name: "Quality Axe", chance: 80 },
		{ name: "Feather-Weight Axe", chance: 50 },
		{ name: "Quality Mace", chance: 80 },
		{ name: "Quality Hammer", chance: 80 },
		{ name: "Claymore", chance: 80 },
		{ name: "Barbarian's Heavy Blade", chance: 80 },
		{ name: "Dwarven Chainmail", chance: 90 },
		{ name: "Dwarven Platemail", chance: 90 },
		{ name: "Quality Iron Shield", chance: 60 },
		{ name: "Kite Shield", chance: 60 },
		{ name: "Fine Helmet", chance: 60 },
		{ name: "Pig Face Basset", chance: 60 },
		{ name: "War Gauntlets", chance: 80 },
		{ name: "Chain Gloves", chance: 80 },
		{ name: "Oak Axe Handle", chance: 5 },
		{ name: "Dwarven Ore", chance: 40 },
		{ name: "Fine Hilt and Guard", chance: 40 },
		{ name: "Spool of Heavy Wire", chance: 40 },
		{ name: "Iron Ore", chance: 40 },
		{ name: "Pure Ore", chance: 40 },
		{ name: "Sheet Metal", chance: 40 },
		{ name: "Steel", chance: 40 },
	],
	"Gun Smith": [
		{ name: "Schematic: Bullets", chance: 75 },
		{ name: "Schematic: Rifled Cannon", chance: 5 },
		{ name: "Clarington Rifle", chance: 50 },
		{ name: "Auto Loading Chamber", chance: 50 },
		{ name: "Fancy Pistol", chance: 50 },
		{ name: "Bullet", chance: 100 },
		{ name: "Revolver", chance: 60 },
		{ name: "Old Revolver", chance: 60 },
		{ name: "Flintlock Pistol", chance: 60 },
		{ name: "Old Flintlock Pistol", chance: 60 },
		{ name: "Shotgun", chance: 50 },
		{ name: "Hunting Rifle", chance: 50 },
		{ name: "Marksman Rifle", chance: 50 },
		{ name: "Rifle", chance: 50 },
		{ name: "Rusted Rifle", chance: 70 },
		{ name: "Black Powder", chance: 70 },
		{ name: "Gun Chassis", chance: 70 },
		{ name: "Revolver Chamber", chance: 70 },
		{ name: "Schematic: Hallucination Grenade", chance: 5 },
		{ name: "Schematic: Electrocution Grenade", chance: 3 },
		{ name: "Schematic: Grenade Launcher", chance: 3 },
		{ name: "Schematic: Time Bomb", chance: 3 },
		{ name: "Schematic: Concussion Grenade", chance: 3 },
		{ name: "Schematic: Paralysis Grenade", chance: 3 },
		{ name: "Schematic: Mustard Gas Grenade", chance: 3 },
		{ name: "Schematic: Plastique", chance: 3 },
		{ name: "Schematic: Detonator", chance: 3 },
		{ name: "Schematic: Flame Thrower", chance: 3 },
		{ name: "Schematic: Mechanized Gun", chance: 3 },
		{ name: "Schematic: Acid Gun", chance: 3 },
		{ name: "Schematic: Accelerator Gun", chance: 3 },
		{ name: "Schematic: Pyrotechnic Gun", chance: 3 },
		{ name: "Schematic: High Velocity Pistol", chance: 3 },
		{ name: "Schematic: Long Range Pistol", chance: 3 },
		{ name: "Schematic: Tranquilizer Gun", chance: 3 },
		{ name: "Schematic: Knock Out Gas", chance: 3 },
	],
	"Magic (General)": [
		{ name: "Scroll of Exiting", chance: 100 },
		{ name: "Scroll of Divine Magic", chance: 100 },
		{ name: "Scroll of Resurrect", chance: 100 },
		{ name: "Heal Lesser Wounds", chance: 100 },
		{ name: "Light Fatigue Restore", chance: 100 },
		{ name: "Greater Fatigue Restore", chance: 100 },
		{ name: "Greater Healing", chance: 100 },
		{ name: "Heal Poison", chance: 100 },
		{ name: "Staff", chance: 100 },
		{ name: "Robes", chance: 100 },
		{ name: "Dread Armour", chance: 80 },
		{ name: "Quality Staff", chance: 80 },
		{ name: "Mage's Dagger", chance: 30 },
		{ name: "Staff of Healing", chance: 33 },
		{ name: "Shaman's Staff", chance: 33 },
		{ name: "Mage's Staff", chance: 33 },
		{ name: "Small Robes", chance: 20 },
		{ name: "Small Oiled Thieves Leather", chance: 10 },
		{ name: "Scroll of Unlocking Cantrip", chance: 22 },
		{ name: "Scroll of Teleportation", chance: 10 },
		{ name: "Scroll of Sense Alignment", chance: 22 },
		{ name: "Scroll of See Contents", chance: 22 },
		{ name: "Scroll of Read Aura", chance: 22 },
		{ name: "Scroll of Divine Magic", chance: 10 },
		{ name: "Scroll of Vitality of Air", chance: 22 },
		{ name: "Scroll of Call Winds", chance: 10 },
		{ name: "Scroll of Stone Throw", chance: 10 },
		{ name: "Scroll of Wall of Fire", chance: 10 },
		{ name: "Scroll of Fireflash", chance: 10 },
		{ name: "Scroll of Purity of Water", chance: 22 },
		{ name: "Scroll of Squall of Ice", chance: 10 },
		{ name: "Scroll of Jolt", chance: 22 },
		{ name: "Scroll of Charm", chance: 22 },
		{ name: "Scroll of Stun", chance: 10 },
		{ name: "Scroll of Drain Will", chance: 10 },
		{ name: "Scroll of Nightmare", chance: 10 },
		{ name: "Scroll of Resist Magick", chance: 10 },
		{ name: "Scroll of Weaken", chance: 10 },
		{ name: "Scroll of Flesh to Stone", chance: 10 },
	],
	"Magic (Light)": [
		{ name: "Scroll of Exiting", chance: 100 },
		{ name: "Scroll of Divine Magic", chance: 100 },
		{ name: "Scroll of Resurrect", chance: 100 },
		{ name: "Heal Lesser Wounds", chance: 100 },
		{ name: "Light Fatigue Restore", chance: 100 },
		{ name: "Greater Healing", chance: 70 },
		{ name: "Greater Fatigue Restore", chance: 70 },
		{ name: "Morgana's Tears", chance: 70 },
		{ name: "Fatigue Slower", chance: 70 },
		{ name: "Essence of Intellect", chance: 100 },
		{ name: "Potion of Haste", chance: 60 },
		{ name: "Fine Steel Dagger", chance: 90 },
		{ name: "Mage's Dagger", chance: 70 },
		{ name: "Quality Staff", chance: 100 },
		{ name: "Staff of Healing", chance: 55 },
		{ name: "Shaman's Staff", chance: 40 },
		{ name: "Mage's Staff", chance: 55 },
		{ name: "Robes", chance: 100 },
		{ name: "Dread Armour", chance: 80 },
		{ name: "Geleam's Helm", chance: 50 },
		{ name: "Fated Ring", chance: 60 },
		{ name: "Dorian Amulet", chance: 80 },
		{ name: "Venom-Shielded Garment", chance: 70 },
		{ name: "Small Venom-Shielded Garment", chance: 10 },
		{ name: "Large Venom-Shielded Garment", chance: 10 },
		{ name: "Oiled Thieves Leather", chance: 70 },
		{ name: "Creep Armour", chance: 40 },
		{ name: "Gnomish Chainmail", chance: 30 },
		{ name: "Small Robes", chance: 20 },
		{ name: "Scroll of Teleportation", chance: 10 },
		{ name: "Scroll of Sense Invisible/Traps", chance: 22 },
		{ name: "Scroll of Divine Magic", chance: 22 },
		{ name: "Scroll of Poison Vapours", chance: 22 },
		{ name: "Scroll of Body of Air", chance: 22 },
		{ name: "Scroll of Call Air Elemental", chance: 10 },
		{ name: "Scroll of Stone Throw", chance: 22 },
		{ name: "Scroll of Body of Stone", chance: 22 },
		{ name: "Scroll of Call Earth Elemental", chance: 10 },
		{ name: "Scroll of Agility of Fire", chance: 22 },
		{ name: "Scroll of Squall of Ice", chance: 22 },
		{ name: "Scroll of Body of Water", chance: 22 },
		{ name: "Scroll of Call Water Elemental", chance: 10 },
		{ name: "Scroll of Stun", chance: 22 },
		{ name: "Scroll of Drain Will", chance: 22 },
		{ name: "Scroll of Resist Magick", chance: 22 },
		{ name: "Scroll of Flesh to Stone", chance: 22 },
		{ name: "Scroll of Charm Beast", chance: 22 },
		{ name: "Scroll of Succour Beast", chance: 22 },
		{ name: "Scroll of Regenerate", chance: 22 },
		{ name: "Scroll of Major Healing", chance: 22 },
		{ name: "Scroll of Sanctuary", chance: 15 },
		{ name: "Scroll of Flash", chance: 22 },
		{ name: "Scroll of Hasten", chance: 22 },
		{ name: "Scroll of Tempus Fugit", chance: 10 },
	],
	"Magic (Dark)": [
		{ name: "Scroll of Exiting", chance: 100 },
		{ name: "Scroll of Divine Magic", chance: 100 },
		{ name: "Scroll of Resurrect", chance: 100 },
		{ name: "Heal Lesser Wounds", chance: 100 },
		{ name: "Light Fatigue Restore", chance: 100 },
		{ name: "Greater Healing", chance: 70 },
		{ name: "Greater Fatigue Restore", chance: 70 },
		{ name: "Fatigue Slower", chance: 80 },
		{ name: "Potion of Haste", chance: 70 },
		{ name: "Liquid of Skin Thickening", chance: 100 },
		{ name: "Kalispi's Venom", chance: 100 },
		{ name: "Fine Steel Dagger", chance: 70 },
		{ name: "Mage's Dagger", chance: 50 },
		{ name: "Dagger of Speed", chance: 50 },
		{ name: "Quality Staff", chance: 80 },
		{ name: "Staff of Healing", chance: 60 },
		{ name: "Shaman's Staff", chance: 70 },
		{ name: "Mage's Staff", chance: 50 },
		{ name: "Fated Ring", chance: 60 },
		{ name: "Dorian Amulet", chance: 40 },
		{ name: "Dread Armour", chance: 80 },
		{ name: "Geleam's Helm", chance: 50 },
		{ name: "Reaper's Axe", chance: 30 },
		{ name: "Inferno Hammer", chance: 30 },
		{ name: "Sword of Sickness", chance: 30 },
		{ name: "Bow of Terror", chance: 30 },
		{ name: "Scroll of Disarm", chance: 25 },
		{ name: "Scroll of Unseen Force", chance: 25 },
		{ name: "Scroll of Spatial Distortion", chance: 25 },
		{ name: "Scroll of Call Winds", chance: 25 },
		{ name: "Scroll of Wall of Fire", chance: 25 },
		{ name: "Scroll of Fireflash", chance: 20 },
		{ name: "Scroll of Body of Fire", chance: 25 },
		{ name: "Scroll of Call Fire Elemental", chance: 10 },
		{ name: "Scroll of Bolt of Lightning", chance: 25 },
		{ name: "Scroll of Disintegrate", chance: 5 },
		{ name: "Scroll of Drain Will", chance: 25 },
		{ name: "Scroll of Dominate Will", chance: 25 },
		{ name: "Scroll of Weaken", chance: 25 },
		{ name: "Scroll of Polymorph", chance: 10 },
		{ name: "Scroll of Control Beast", chance: 20 },
		{ name: "Scroll of Conjure Spirit", chance: 25 },
		{ name: "Scroll of Summon Undead", chance: 25 },
		{ name: "Scroll of Create Undead", chance: 25 },
		{ name: "Scroll of Phantasmal Fiend", chance: 25 },
		{ name: "Scroll of Invisibility", chance: 10 },
		{ name: "Scroll of Hellgate", chance: 15 },
		{ name: "Scroll of Familiar", chance: 10 },
	],
	"Black Market": [
		{ name: "Scroll of Exiting", chance: 100 },
		{ name: "Scroll of Divine Magic", chance: 100 },
		{ name: "Scroll of Resurrect", chance: 100 },
		{ name: "Dorian Amulet", chance: 5 },
		{ name: "Medallion of Beauty", chance: 5 },		
		{ name: "Black Diamond", chance: 15 },
		{ name: "Morgana's Tears", chance: 30 },
		{ name: "Fatigue Slower", chance: 30 },
		{ name: "Essence of Intellect", chance: 30 },
		{ name: "Potion of Haste", chance: 30 },
		{ name: "Liquid of Skin Thickening", chance: 30 },
		{ name: "Kalispi's Venom", chance: 30 },
		{ name: "Oiled Chainmail", chance: 70 },
		{ name: "Small Oiled Chainmail", chance: 70 },
		{ name: "Small Oiled Thieves Leather", chance: 70 },
		{ name: "Oiled Thieves Leather", chance: 70 },
		{ name: "Light-Fingered Gauntlets", chance: 70 },
		{ name: "Absinthe", chance: 100 },
		{ name: "Small Robe of the Chameleon", chance: 70 },
		{ name: "Lockpicks", chance: 70 },
		{ name: "Dagger", chance: 70 },
		{ name: "Rusty Dagger", chance: 70 },
		{ name: "Sword", chance: 70 },
		{ name: "Rusty Sword", chance: 70 },
		{ name: "Axe", chance: 70 },
		{ name: "Rusty Axe", chance: 70 },
		{ name: "Mace", chance: 70 },
		{ name: "Rusty Mace", chance: 70 },
		{ name: "Hammer", chance: 70 },
		{ name: "Rusty Hammer", chance: 70 },
		{ name: "Old Revolver", chance: 70 },
		{ name: "Old Flintlock Pistol", chance: 70 },
		{ name: "Rusty Broadsword", chance: 70 },
		{ name: "Arrow", chance: 70 },
		{ name: "Bullet", chance: 70 },
		{ name: "Serrated Chakram", chance: 50 },
		{ name: "Bandages", chance: 100 },
	],
	"Spectals Maker": [
		{ name: "Eye Glasses", chance: 100 },
	],
	"Nomad": [
		{ name: "Kalispi's Venom", chance: 100 },
		{ name: "Liquid of Skin Thickening", chance: 100 },
		{ name: "Potion of Haste", chance: 100 },
		{ name: "Essence of Intellect", chance: 100 },
		{ name: "Morgana's Tears", chance: 100 },
		{ name: "Heal Poison", chance: 100 },
		{ name: "Light Fatigue Restore", chance: 100 },
		{ name: "Heal Lesser Wounds", chance: 100 },
		{ name: "Fatigue Slower", chance: 50 },
		{ name: "Greater Fatigue Restore", chance: 60 },
		{ name: "Greater Healing", chance: 60 },
		{ name: "Magick Robes", chance: 13 },
		{ name: "Small Robe of the Chameleon", chance: 13 },
		{ name: "Shadowing Robes", chance: 13 },
		{ name: "Dark Helm", chance: 9 },
		{ name: "Geleam's Helm", chance: 9 },
		{ name: "Helm of Light", chance: 9 },
		{ name: "Light-Fingered Gauntlets", chance: 10 },
		{ name: "Enchanted War Boots", chance: 10 },
		{ name: "Mystical Chakram", chance: 10 },
		{ name: "Filament Sword", chance: 10 },
		{ name: "Mage's Staff", chance: 20 },
		{ name: "Bow of Terror", chance: 10 },
		{ name: "Elven Hunter's Bow", chance: 10 },
		{ name: "Sword of Sickness", chance: 10 },
		{ name: "Sword of Air", chance: 10 },
		{ name: "Inferno Hammer", chance: 10 },
		{ name: "Crushing Hammer", chance: 10 },
		{ name: "Axe of Strength", chance: 10 },
		{ name: "Reaper's Axe", chance: 10 },
		{ name: "Dagger of Speed", chance: 10 },
		{ name: "Mage's Dagger", chance: 10 },
		{ name: "Arcane Ring", chance: 1 },
		{ name: "Arcane Gauntlets", chance: 1 },
		{ name: "Arcane Helmet", chance: 1 },
		{ name: "Arcane Shield", chance: 1 },
		{ name: "Arcane Platemail", chance: 1 },
		{ name: "Small Arcane Platemail", chance: 1 },
		{ name: "Arcane Traveler's Cloak", chance: 1 },
		{ name: "Small Arcane Traveler's Cloak", chance: 1 },
		{ name: "Arcane Robes", chance: 1 },
		{ name: "Small Arcane Robes", chance: 1 },
		{ name: "Arcane Chainmail", chance: 1 },
		{ name: "Small Arcane Chainmail", chance: 1 },
		{ name: "Arcane Leather Armour", chance: 1 },
		{ name: "Small Arcane Leather Armour", chance: 1 },
		{ name: "Large Arcane Leather Armour", chance: 1 },
		{ name: "Arcane Staff", chance: 1 },
		{ name: "Arcane Bow", chance: 1 },
		{ name: "Arcane Great Sword", chance: 1 },
		{ name: "Arcane Mace", chance: 1 },
		{ name: "Arcane Axe", chance: 1 },
		{ name: "Arcane Sword", chance: 1 },
		{ name: "Arcane Dagger", chance: 1 },
	],

// UNUSED

	"Starting Barter": [
		{ name: "Dagger", chance: 100 },
		{ name: "Sword", chance: 100 },
		{ name: "Axe", chance: 100 },
		{ name: "Mace", chance: 100 },
		{ name: "Staff", chance: 100 },
		{ name: "Fine Steel Dagger", chance: 100 },
		{ name: "Quality Sword", chance: 100 },
		{ name: "Rapier", chance: 100 },
		{ name: "Short Sword", chance: 100 },
		{ name: "Quality Mace", chance: 100 },
		{ name: "Flintlock Pistol", chance: 100 },
		{ name: "Short Bow", chance: 100 },
		{ name: "Rifle", chance: 100 },
		{ name: "Boomerang", chance: 100 },
		{ name: "Arrow", chance: 100 },
		{ name: "Bullet", chance: 100 },
		{ name: "Battered Wooden Shield", chance: 100 },
		{ name: "Helmet", chance: 100 },
		{ name: "Gauntlets", chance: 100 },
		{ name: "Boots", chance: 100 },
		{ name: "Suede Jacket", chance: 100 },
		{ name: "Small Suede Jacket", chance: 100 },
		{ name: "Robes", chance: 100 },
		{ name: "Small Robes", chance: 100 },
		{ name: "Jacket", chance: 100 },
		{ name: "Small Jacket", chance: 100 },
		{ name: "Copper Ring", chance: 100 },
		{ name: "Elegant Dress", chance: 100 },
		{ name: "Wooden Ring", chance: 100 },
		{ name: "Silver Ring", chance: 100 },
		{ name: "Healing Salve", chance: 100 },
		{ name: "Heal Lesser Wounds", chance: 100 },
		{ name: "Light Fatigue Restore", chance: 100 },
		{ name: "Heal Poison", chance: 100 },
		{ name: "Lockpicks", chance: 100 },
	],
	"Gnomish Merchant": [
		{ name: "Dagger", chance: 80 },
		{ name: "Fine Steel Dagger", chance: 80 },
		{ name: "Battery", chance: 80 },
		{ name: "Short Bow", chance: 80 },
		{ name: "Staff", chance: 80 },
		{ name: "Small Heavy Wool Clothes", chance: 80 },
		{ name: "Small Suede Jacket", chance: 80 },
		{ name: "Small Wool Jacket", chance: 80 },
		{ name: "Small Jacket", chance: 80 },
		{ name: "Small Leather Armour", chance: 70 },
		{ name: "Small Robes", chance: 70 },
		{ name: "Small Rustic Finery", chance: 70 },
		{ name: "Small Nice Suit", chance: 60 },
		{ name: "Small Smoking Jacket", chance: 50 },
		{ name: "Small Robe of the Chameleon", chance: 50 },
		{ name: "Key Ring", chance: 50 },
		{ name: "Staff of Healing", chance: 50 },
		{ name: "Shaman's Staff", chance: 50 },
		{ name: "Tincture of Arnica", chance: 33 },
		{ name: "Rheumatism Cure", chance: 33 },
		{ name: "Scroll of Unlocking Cantrip", chance: 20 },
		{ name: "Scroll of Sense Alignment", chance: 20 },
		{ name: "Scroll of See Contents", chance: 20 },
		{ name: "Scroll of Read Aura", chance: 20 },
		{ name: "Scroll of Sense Invisible/Traps", chance: 20 },
		{ name: "Scroll of Divine Magic", chance: 20 },
		{ name: "Scroll of Resist Magick", chance: 20 },
		{ name: "Scroll of Succour Beast", chance: 20 },
		{ name: "Scroll of Minor Healing", chance: 20 },
		{ name: "Scroll of Halt Poison", chance: 20 },
		{ name: "Bandages", chance: 100 },
	],
};